Repository dpc-sdp/ripple, pull requests merged in 2018-11, with the labels that each got.

#112 [SDPA-925] Updated search icon, text and input box alignment.
  packages/Molecules/Search/SearchForm.vue
  packages/Organisms/SiteHeader/search.vue
Labels: ready for test

#115 [SDPA-1198] Added mobile padding to sitemap component.
  packages/Molecules/Sitemap/index.vue
  src/storybook-components/PageSitemap.vue
  src/storybook-components/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#122 Feature/1.0.0 alpha.25
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#121 [SDPA-765] Added timeline component.
  package-lock.json
  package.json
  packages/Molecules/Timeline/.npmignore
  packages/Molecules/Timeline/LICENSE
  packages/Molecules/Timeline/README.md
  packages/Molecules/Timeline/Timeline.vue
  packages/Molecules/Timeline/index.js
  packages/Molecules/Timeline/package.json
  packages/Molecules/Timeline/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#119 [SDPA-1240] Added external link icon to RplRelatedLinks and RplWhatsN…
  packages/Molecules/RelatedLinks/index.vue
  packages/Molecules/WhatsNext/index.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#118 [SPDA-1227] refactored contact to use list component internally
  packages/Molecules/Contact/index.vue
  packages/Molecules/List/index.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#120 [SDPA-1241] Adds right padding to rpl-hero-banner__left
  packages/Organisms/HeroBanner/HeroBanner.vue
Labels: ready to be merged

#123 [SDPA-1244] added mobile padding to RplUpdatedDate
  packages/Organisms/UpdatedDate/index.vue
  src/storybook-components/Page.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#125 [SDPA-1275] Changed top spacing from search form title to component c…
  packages/Molecules/Search/SearchForm.vue
Labels: ready for test

#126 Release/v1.0.0 alpha.26
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#127 [SDPA-1240] TextLink always uses external_link icon if link is external.
  packages/Atoms/Link/TextLink.vue
  packages/Molecules/RelatedLinks/index.vue
  packages/Molecules/WhatsNext/index.vue
Labels: needs review

#128 Release v1.0.0-alpha.27
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#130 [SDPA-642] [SDPA-934] Updated spacing of search form
  packages/Molecules/Search/SearchForm.vue
  src/storybook-components/Page.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#129 [SDPA-348] news listing padding
  .storybook/config.js
  packages/Molecules/Timeline/Timeline.vue
  packages/Organisms/News/NewsListing.vue
  src/storybook-components/Page.vue
  src/storybook-components/scss/story.scss
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#142 Release/1.0.0 alpha.29
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#144 Release/1.0.0 alpha.30
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#132 [SDPA-986] Updated logo padding to prevent touching between logo and …
  packages/Organisms/HeroBanner/HeroBanner.vue
  src/storybook-components/PageHeroGraphics.vue
  src/storybook-components/stories.js
Labels: ready to be merged

#141 [SDPA-784] Updated anchor links to display as single column.
  packages/Molecules/AnchorLinks/index.vue
Labels: ready for test

#140 [SDPA-1023] Updated image gallery.
  packages/Organisms/ImageGallery/ImageGallery.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#145 Feature/sdpa 1077 reduce breadcrumb margin
  packages/Atoms/Global/scss/_variables.scss
  packages/Molecules/Breadcrumbs/index.vue
  packages/Organisms/HeroBanner/HeroBanner.vue
Labels: ready to be merged

#143 [SDPA-1346] Update card content to fix positioning on IE.
  packages/Molecules/Card/CardContent.vue
Labels: ready to be merged

#146 Release/1.0.0.alpha.31
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#134 Feature/sdpa 749 global alerts and warnings
  package-lock.json
  packages/Atoms/Icon/assets/img/rpl_icon_alert_fire.svg
  packages/Atoms/Icon/assets/img/rpl_icon_alert_flood.svg
  packages/Atoms/Icon/assets/img/rpl_icon_alert_high_temperature.svg
  packages/Atoms/Icon/assets/img/rpl_icon_alert_information.svg
  packages/Atoms/Icon/assets/img/rpl_icon_alert_lightning.svg
  packages/Atoms/Icon/assets/img/rpl_icon_alert_medical.svg
  packages/Atoms/Icon/assets/img/rpl_icon_alert_smoke.svg
  packages/Atoms/Icon/assets/img/rpl_icon_alert_transport.svg
  packages/Atoms/Icon/assets/img/rpl_icon_success.svg
  packages/Molecules/Alert/Alert.vue
  packages/Molecules/Alert/AlertBase.vue
  packages/Molecules/Alert/README.md
  packages/Molecules/Alert/package.json
  packages/Molecules/Alert/stories.js
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#147 [SDPA-1382] Adds missing status to grants and cross circle icon
  packages/Atoms/Icon/assets/img/rpl_icon_cross_circle.svg
  packages/Organisms/Grants/GrantsOverview.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test
