Repository dpc-sdp/ripple, pull requests merged in 2018-10, with the labels that each got.

#80 [SDPA-912] Events Search Page - Ripple
  README.md
  packages/Atoms/Icon/stories.js
  packages/Molecules/Layout/PageLayout.vue
  packages/Molecules/Search/README.md
  packages/Molecules/Search/SearchForm.vue
  packages/Molecules/Search/SearchResults.vue
  packages/Molecules/Search/stories.js
  src/storybook-components/EventSearchPage.vue
  src/storybook-components/_data/demoData.js
  src/storybook-components/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#95 v1.0.0-alpha.20
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
  scripts/generate-package/package_template.json
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#98 Feature/sdpa 973 banner padding
  package-lock.json
  packages/Molecules/Layout/PageLayout.vue
  packages/Organisms/HeroBanner/HeroBanner.vue
  src/storybook-components/PageHeroGraphics.vue
  src/storybook-components/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#96 Feature/sdpa 1068 card event topic theme
  packages/Molecules/Card/CardEvent.vue
  packages/Molecules/Card/CardPromotion.vue
  packages/Molecules/Card/stories.js
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#102 [SDPA-1119] Removed topic from CardEvent.
  packages/Molecules/Card/CardEvent.vue
  packages/Molecules/Card/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#99 [SDPA-636] Added Alert package and AlertBase component.
  package-lock.json
  package.json
  packages/Molecules/Alert/.npmignore
  packages/Molecules/Alert/Alert.vue
  packages/Molecules/Alert/AlertBase.vue
  packages/Molecules/Alert/LICENSE
  packages/Molecules/Alert/README.md
  packages/Molecules/Alert/index.js
  packages/Molecules/Alert/package.json
  packages/Molecules/Alert/stories.js
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  src/storybook-components/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#104 [SDPA-1119] Removed stray topic variable call.
  packages/Molecules/Card/CardEvent.vue
Labels: needs review

#103 Release/1.0.0 alpha.21
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#105 Release/1.0.0 alpha.22
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#97 [SDPA-747] grant overview
  package-lock.json
  package.json
  packages/Atoms/Icon/assets/img/rpl_icon_user.svg
  packages/Organisms/Grants/.npmignore
  packages/Organisms/Grants/GrantsOverview.vue
  packages/Organisms/Grants/LICENSE
  packages/Organisms/Grants/README.md
  packages/Organisms/Grants/index.js
  packages/Organisms/Grants/package.json
  packages/Organisms/Grants/stories.js
  scripts/generate-package/stories_template.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#106 [SDPA-1155] Fixed card.querySelector is not a function error
  packages/Atoms/Global/mixins/cardtrimfield.js
Labels: needs review

#108 v1.0.0-alpha.23
  lerna.json
  package-lock.json
  package.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#110 [SDPA-1160] Updated card trimming to refresh more often.
  package-lock.json
  packages/Molecules/Card/CardEvent.vue
  packages/Molecules/Card/CardKeydates.vue
  packages/Molecules/Card/CardPromotion.vue
  packages/Molecules/Card/mixins/cardtrimfield.js
  packages/Molecules/Card/no-ssr/CardCarousel.vue
  packages/Molecules/Card/package.json
  src/storybook-components/PageCardTrim.vue
  src/storybook-components/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#113 [SDPA-1111] Update CTA card with fixed image size.
  packages/Molecules/Card/CardContent.vue
  packages/Molecules/Card/CardCta.vue
Labels: ready for test

#111 [SDPA-1178] Fixed IE11 alt+tab bug. Route change removes link focus.
  packages/Organisms/SiteHeader/index.vue
Labels: ready for test
