Repository dpc-sdp/ripple, pull requests merged in 2018-09, with the labels that each got.

#54 v1.0.0-alpha.12
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#52 [SDPA-880] Removed hardcoded color in svg icon.
  packages/Atoms/Icon/assets/img/external_link.svg
  packages/Atoms/Icon/assets/img/instagram.svg
  packages/Atoms/Icon/assets/img/linkedin.svg
  packages/Atoms/Icon/stories.js
  src/storybook-components/Icons.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#51 Feature/sdpa 865 bggraphic
  packages/Molecules/Layout/PageLayout.vue
  packages/Molecules/Layout/stories.js
  src/storybook-components/CampaignPage.vue
  src/storybook-components/Page.vue
  src/storybook-components/SiteLayout.vue
  src/storybook-components/_data/demoData.js
  static/bggraphic.png
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#49 [SDPA-835] Search fix
  README.md
  package-lock.json
  packages/Atoms/Global/components/Divider.vue
  packages/Atoms/Global/index.js
  packages/Atoms/Global/stories.js
  packages/Molecules/Pagination/index.vue
  packages/Molecules/Pagination/stories.js
  packages/Molecules/Search/SearchForm.vue
  packages/Molecules/Search/SearchResult.vue
  packages/Molecules/Search/SearchResults.vue
  packages/Molecules/Search/index.js
  packages/Molecules/Search/stories.js
  src/storybook-components/Page.vue
  src/storybook-components/README.md
  src/storybook-components/SearchPage.vue
  src/storybook-components/_data/demoData.js
  src/storybook-components/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#55 [SDPA-868] Added background graphic to Hero Banner.
  packages/Organisms/HeroBanner/index.vue
  packages/Organisms/HeroBanner/stories.js
  src/storybook-components/_data/demoData.js
  static/bggraphiclower.png
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#57 1.0.0 Alpha 13
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#58 [SDPA-865] Fix: Allow undefined backgroundImage on PageLayout.
  packages/Molecules/Layout/PageLayout.vue
  packages/Molecules/Layout/stories.js
  src/storybook-components/CampaignPage.vue
  src/storybook-components/SiteLayout.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#59 v1.0.0-alpha.14
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#56 Feature/sdpa 858 hero banner logo
  packages/Organisms/HeroBanner/index.vue
  packages/Organisms/HeroBanner/stories.js
  src/storybook-components/_data/demoData.js
  static/herologo.png
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#63 Feature/sdpa 722 fixed font weight firefox
  packages/Atoms/Global/scss/_global.scss
  packages/Atoms/Global/scss/_typography.scss
Labels: ready for test

#62 Feature/v1.0.0 alpha.15
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#64 [SDPA-654] Added back to top button.
  packages/Atoms/Global/scss/_transition.scss
  packages/Molecules/Layout/BackToTop.vue
  packages/Molecules/Layout/BaseLayout.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#65 [SDPA-792] card cta
  packages/Atoms/Global/README.md
  packages/Molecules/Card/CardContent.vue
  packages/Molecules/Card/CardCta.vue
  packages/Molecules/Card/README.md
  packages/Molecules/Card/ReadmeCardContent.md
  packages/Molecules/Card/index.js
  packages/Molecules/Card/stories.js
  packages/Molecules/Search/README.md
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#75 Fixed lagoon npm install error
  .npmrc
  Dockerfile
  Dockerfile.local
  Dockerfile.test
Labels: needs review

#66 [SDPA-906] list
  package-lock.json
  package.json
  packages/Molecules/List/.npmignore
  packages/Molecules/List/LICENSE
  packages/Molecules/List/README.md
  packages/Molecules/List/index.vue
  packages/Molecules/List/package.json
  packages/Molecules/List/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#68 [SDPA-856] card carousel
  package-lock.json
  packages/Atoms/Global/package.json
  packages/Molecules/Card/CardCarousel.vue
  packages/Molecules/Card/ReadmeCardContent.md
  packages/Molecules/Card/index.js
  packages/Molecules/Card/stories.js
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#74 [SDPA-942] logos for footer
  packages/Organisms/SiteFooter/index.vue
  packages/Organisms/SiteFooter/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#71 [SDPA-939] introduction banner
  packages/Organisms/HeroBanner/HeroBanner.vue
  packages/Organisms/HeroBanner/IntroBanner.vue
  packages/Organisms/HeroBanner/index.js
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/HeroBanner/stories.js
  src/storybook-components/_data/demoData.js
Labels: ready for test

#70 [SDPA-918] latest events
  package-lock.json
  package.json
  packages/Organisms/Event/.npmignore
  packages/Organisms/Event/LICENSE
  packages/Organisms/Event/LatestEvents.vue
  packages/Organisms/Event/README.md
  packages/Organisms/Event/index.js
  packages/Organisms/Event/package.json
  packages/Organisms/Event/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#81 [SDPA-997] Added vicpol form changes
  package-lock.json
  packages/Molecules/Form/index.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#82 v1.0.0-alpha.16
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#85 [SDPA-1001] Changed card carousel can be used client side only
  packages/Molecules/Card/index.js
  packages/Molecules/Card/no-ssr/CardCarousel.vue
  packages/Molecules/Card/no-ssr/index.js
  packages/Molecules/Card/stories.js
  packages/Molecules/List/index.vue
  src/storybook-components/Page.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#86 Release/1.0.0 alpha.17
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#89 [SDPA-905] Added new icons. Fixed colour issue on success icon.
  packages/Atoms/Icon/Icon.vue
  packages/Atoms/Icon/assets/img/rpl_icon_accessible.svg
  packages/Atoms/Icon/assets/img/rpl_icon_child_friendly.svg
  packages/Atoms/Icon/assets/img/rpl_icon_dollar_negative.svg
  packages/Atoms/Icon/assets/img/rpl_icon_free.svg
  packages/Atoms/Icon/assets/img/rpl_icon_senior.svg
  packages/Atoms/Icon/assets/img/rpl_icon_success.svg
  packages/Atoms/Icon/assets/img/rpl_icon_webinar.svg
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#88 [SDPA-969] Added date range to CardEvent.
  packages/Atoms/Global/mixins/formatdate.js
  packages/Molecules/Card/CardEvent.vue
  packages/Molecules/Card/stories.js
  packages/Organisms/Event/LatestEvents.vue
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#83 [SDPA-971] date picker
  package-lock.json
  packages/Molecules/Form/fields/fieldRpldatepicker.vue
  packages/Molecules/Form/formPikaday.vue
  packages/Molecules/Form/index.vue
  packages/Molecules/Form/package.json
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#87 Feature/component generate
  CONTRIBUTING.md
  package.json
  scripts/generate-component/.npmignore
  scripts/generate-component/LICENSE
  scripts/generate-component/component_template.vue
  scripts/generate-component/package_template.json
  scripts/generate-component/stories_template.js
  scripts/generate-package/.npmignore
  scripts/generate-package/LICENSE
  scripts/generate-package/generate-package.js
  scripts/generate-package/index_template.js
  scripts/generate-package/package_template.json
  scripts/generate-package/package_template.vue
  scripts/generate-package/stories_template.js
Labels: needs review

#91 [SDPA-1012] Fixed error of undefined prop
  packages/Organisms/HeroBanner/IntroBanner.vue
Labels: needs review

#92 Release/1.0.0 alpha.19
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/NewsListing/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review
