Repository dpc-sdp/ripple, pull requests merged in 2019-11, with the labels that each got.

#560 [SDPA-3209] Added error capture and UI handling
  packages/components/Atoms/Global/README.md
  packages/components/Atoms/Global/components/DevError.vue
  packages/components/Atoms/Global/components/dev-error.stories.mdx
  packages/components/Atoms/Global/components/divider.stories.js
  packages/components/Atoms/Global/index.js
  packages/components/Atoms/Global/mixins/catch-child-error.js
  packages/components/Atoms/Global/scss/settings/_color.scss
  packages/components/Atoms/Global/stories.js
  packages/components/Atoms/Grid/Col.vue
  packages/components/Atoms/Grid/__tests__/col.test.js
  packages/components/Molecules/Card/CardBox.vue
  packages/components/Molecules/Card/CardContent.vue
  packages/components/Molecules/Card/CardNavigationFeatured.vue
  packages/components/Molecules/Card/no-ssr/CardCarousel.vue
  packages/ripple-nuxt-tide/lib/components/AppSidebar.vue
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/modules/landing-page/pages/index.vue
  packages/ripple-nuxt-tide/modules/publication/pages/index.vue
  packages/ripple-nuxt-ui/lib/module.js
  packages/ripple-nuxt-ui/lib/templates/plugin.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#565 [SDPL-88] Field select letter
  packages/components/Molecules/Form/__tests__/fieldRplOptionbutton.test.js
  packages/components/Molecules/Form/fields/fieldRploptionbutton.vue
  packages/components/Molecules/Form/index.vue
  packages/components/Molecules/Form/stories.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#569 [SDPL-89] Meta tag solid
  packages/components/Atoms/MetaTag/index.vue
  packages/components/Atoms/MetaTag/stories.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#578 Fix rpl-select not emitting events on mobile
  packages/components/Molecules/Form/Select.vue
Labels: ready to be merged

#590 [SDPA-3169] updates ripple logo
  README.md
  docs/sdp-ripple.jpg
  docs/sdp-ripple.png
Labels: needs review

#587 [SDPA-3351] jsonapi cache
  packages/ripple-nuxt-tide/lib/core/tide.js
Labels: ready for test

#592 [SDPUP-1097] homepage error code
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/templates/axios.js
Labels: ready for test

#583 [SDPA-3307][SDPA-3341][SDPA-3415] [SDPA-3435] print publication issue
  examples/vic-gov-au/test/e2e/integration/core-modules/publication/publication.feature
  packages/components/Atoms/Global/scss/tools/_grid.scss
  packages/components/Molecules/AnchorLinks/index.vue
  packages/components/Molecules/Card/CardBox.vue
  packages/components/Molecules/Card/CardContent.vue
  packages/components/Molecules/Card/CardNavigationFeatured.vue
  packages/components/Molecules/Card/no-ssr/CardCarousel.vue
  packages/components/Molecules/Form/index.vue
  packages/components/Molecules/Layout/PageLayout.vue
  packages/components/Molecules/Map/Map.vue
  packages/components/Organisms/CallToAction/index.vue
  packages/components/Organisms/HeroBanner/HeroBanner.vue
  packages/components/Organisms/ImageGallery/no-ssr/ImageGallery.vue
  packages/components/Organisms/News/NewsListing.vue
  packages/components/Organisms/Publication/PublicationImage.vue
  packages/create-ripple-app/template/_example/tide/modules/event/pages/index.vue
  packages/ripple-nuxt-tide/lib/components/AppContentRating.vue
  packages/ripple-nuxt-tide/modules/event/pages/index.vue
  packages/ripple-nuxt-tide/modules/grant/pages/index.vue
  packages/ripple-nuxt-tide/modules/landing-page/pages/index.vue
  packages/ripple-nuxt-tide/modules/media/components/EmbeddedVideo.vue
  packages/ripple-nuxt-tide/modules/news/pages/index.vue
  packages/ripple-nuxt-tide/modules/page/pages/index.vue
  packages/ripple-nuxt-tide/modules/profile/pages/index.vue
  packages/ripple-nuxt-tide/modules/publication/pages/PrintAll.vue
  packages/ripple-nuxt-tide/modules/publication/pages/index.vue
  packages/ripple-test-tools/step_definitions/common/modules/events.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#543 [SDPA-3114] Add print publication feature.
  examples/vic-gov-au/test/e2e/integration/core-modules/publication/publication.feature
  packages/components/Atoms/Global/scss/tools/_grid.scss
  packages/components/Molecules/AnchorLinks/index.vue
  packages/components/Molecules/Card/CardBox.vue
  packages/components/Molecules/Card/CardContent.vue
  packages/components/Molecules/Card/CardNavigationFeatured.vue
  packages/components/Molecules/Card/no-ssr/CardCarousel.vue
  packages/components/Molecules/Form/index.vue
  packages/components/Molecules/Layout/PageLayout.vue
  packages/components/Molecules/Map/Map.vue
  packages/components/Organisms/CallToAction/index.vue
  packages/components/Organisms/HeroBanner/HeroBanner.vue
  packages/components/Organisms/ImageGallery/no-ssr/ImageGallery.vue
  packages/components/Organisms/News/NewsListing.vue
  packages/components/Organisms/Publication/PublicationDownloadPrint.vue
  packages/components/Organisms/Publication/PublicationImage.vue
  packages/components/Organisms/Publication/stories.js
  packages/create-ripple-app/template/_example/tide/modules/event/pages/index.vue
  packages/ripple-nuxt-tide/lib/components/AppContentRating.vue
  packages/ripple-nuxt-tide/modules/event/pages/index.vue
  packages/ripple-nuxt-tide/modules/grant/pages/index.vue
  packages/ripple-nuxt-tide/modules/landing-page/pages/index.vue
  packages/ripple-nuxt-tide/modules/media/components/EmbeddedVideo.vue
  packages/ripple-nuxt-tide/modules/news/pages/index.vue
  packages/ripple-nuxt-tide/modules/page/pages/index.vue
  packages/ripple-nuxt-tide/modules/profile/pages/index.vue
  packages/ripple-nuxt-tide/modules/publication/module.js
  packages/ripple-nuxt-tide/modules/publication/pages/PrintAll.vue
  packages/ripple-nuxt-tide/modules/publication/pages/index.vue
  packages/ripple-nuxt-tide/modules/publication/templates/router-middleware.js
  packages/ripple-nuxt-tide/modules/publication/tide.middleware.js
  packages/ripple-test-tools/step_definitions/common/components.js
  packages/ripple-test-tools/step_definitions/common/global.js
  packages/ripple-test-tools/step_definitions/common/modules/events.js
  packages/ripple-test-tools/step_definitions/common/navigation.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#577 Make all e2e test pass. Add search e2e tests
  .circleci/config.yml
  examples/basic-examples/test/e2e/integration/custom/error-page.feature
  examples/vic-gov-au/cypress.json
  examples/vic-gov-au/package.json
  examples/vic-gov-au/test/e2e/fixtures/authenticatedContent/1-FE-auth-content-4.yml
  examples/vic-gov-au/test/e2e/fixtures/landingPage/complex.json
  examples/vic-gov-au/test/e2e/fixtures/landingPage/draft.json
  examples/vic-gov-au/test/e2e/fixtures/landingPage/simple.json
  examples/vic-gov-au/test/e2e/fixtures/page/8-BE-page-1-basic-page.yml
  examples/vic-gov-au/test/e2e/fixtures/profile/4-BE-Profile-1.html
  examples/vic-gov-au/test/e2e/fixtures/search/sitesearch-filters.json
  examples/vic-gov-au/test/e2e/fixtures/search/sitesearch.json
  examples/vic-gov-au/test/e2e/integration/core-modules/authenticatedContent/authenticated-content.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/authenticatedContent/authenticated-content/hooks.js
  examples/vic-gov-au/test/e2e/integration/core-modules/authenticatedContent/authenticated-content/step_definition.js
  examples/vic-gov-au/test/e2e/integration/core-modules/event/event.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/event/event/step_definition.js
  examples/vic-gov-au/test/e2e/integration/core-modules/grant/grant.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/news/news.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/page/page.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/profile/profile.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/search/sitesearch.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/site/sitemap.feature
  examples/vic-gov-au/test/e2e/integration/smoke/DemoLandingPage.feature
  examples/vic-gov-au/test/e2e/integration/smoke/elasticsearch.feature
  examples/vic-gov-au/test/e2e/integration/smoke/tide-is-up.feature
  examples/vic-gov-au/test/e2e/plugins/index.js
  packages/ripple-nuxt-tide/lib/pages/Sitemap.vue
  packages/ripple-test-tools/index.js
  packages/ripple-test-tools/step_definitions/common/components.js
  packages/ripple-test-tools/step_definitions/common/index.js
  packages/ripple-test-tools/step_definitions/common/modules/profile.js
  packages/ripple-test-tools/step_definitions/common/modules/search.js
  packages/ripple-test-tools/step_definitions/common/navigation.js
  packages/ripple-test-tools/step_definitions/common/utils.js
  packages/ripple-test-tools/tide-admin/index.js
  packages/ripple-test-tools/tide-admin/page-models.js
Labels: ready for test

#593 Fix/ripple sass settings
  packages/components/Molecules/Card/CardNavigationFeatured.vue
  packages/components/Molecules/RelatedLinks/index.vue
  packages/components/Organisms/SiteHeader/index.vue
  packages/components/Organisms/SiteHeader/menu.vue
  packages/components/Organisms/SiteSectionNavigation/index.vue
  packages/components/Organisms/SiteSectionNavigation/menu.vue
Labels: ready to be merged

#596 Added debugging support for ripple nuxt examples dev env
  examples/basic-examples/nuxt.config.js
  examples/vic-gov-au/nuxt.config.js
Labels: ready to be merged

#598 [SDPA-3449] IE11 video transcript
  packages/components/Organisms/Markup/Markup.vue
  packages/components/Organisms/Markup/markup-transpiler.js
  packages/ripple-nuxt-tide/lib/config/markup-plugins.js
  packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
  packages/ripple-nuxt-tide/test/unit/markup-transpiler.test.js
Labels: ready to be merged

#599 [SDPA-3469] Added Footer logo onoff option in nuxt config
  packages/components/Atoms/Global/index.js
  packages/components/Organisms/SiteFooter/SiteFooter.vue
  packages/ripple-nuxt-ui/lib/templates/plugin.js
Labels: ready for test

#600 [SDPSUP-1118] [SDPA-3400]Update the webform conditional logic (#594)
  packages/ripple-nuxt-tide/lib/core/mapping.js
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/server-middleware/request-log.js
  packages/ripple-nuxt-tide/lib/templates/axios.js
  packages/ripple-nuxt-tide/modules/webform/conditional-logic.js
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
  packages/ripple-nuxt-tide/test/unit/mapping.test.js
  packages/ripple-nuxt-tide/test/unit/webform.test.js
Labels: ready to be merged

#604 [SDPA-3518] Added nuxt robots to new project
  packages/create-ripple-app/template/_package.json
  packages/create-ripple-app/template/nuxt/nuxt.config.js
  packages/create-ripple-app/template/nuxt/robots.js
Labels: ready to be merged

#601 Fix placeholder not configurable for fieldRplSelect
  packages/components/Molecules/Form/Select.vue
  packages/components/Molecules/Form/fields/fieldRplselect.vue
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#602 [SDPL-169] Adds search icon for input field
  packages/components/Molecules/Form/index.vue
  packages/components/Molecules/Form/stories.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#603 [SDPL-169] Adds border radius to option group
  packages/components/Molecules/Form/fields/fieldRplclearform.vue
  packages/components/Molecules/Form/fields/fieldRploptionbutton.vue
  packages/components/Molecules/ListGroup/index.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged
