Repository dpc-sdp/ripple, pull requests merged in 2019-03, with the labels that each got.

#276 [SDPA-2078] Use loading event for show/hide submit loader.
  packages/Molecules/Form/fields/fieldRplsubmitloader.vue
  packages/Molecules/Form/index.vue
Labels: ready to be merged

#279 [SDPA-1900] Card Carousel props added to define cards to show.
  packages/Atoms/Global/mixins/breakpoint.js
  packages/Molecules/Card/no-ssr/CardCarousel.vue
  packages/Molecules/Card/stories.js
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#275 [SDPA-1870] Fill select fields on load if the model already has a value.
  packages/Molecules/Form/fields/fieldRplchecklist.vue
  packages/Molecules/Form/fields/fieldRplselect.vue
  packages/Molecules/Form/index.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#281 [SDPA-2106] Clear search term on clearform event.
  packages/Molecules/Form/index.vue
  packages/Molecules/Search/SearchForm.vue
  src/storybook-components/_data/demoData.js
Labels: ready to be merged

#277 [SDPA-1941] Updates vue social sharing to patched version.
  package-lock.json
  packages/Molecules/ShareThis/package.json
Labels: ready to be merged

#282 [SDPA-2110] Adds missing filetype icons.
  packages/Atoms/Icon/assets/img/rpl_icon_ai.svg
  packages/Atoms/Icon/assets/img/rpl_icon_eps.svg
  packages/Atoms/Icon/assets/img/rpl_icon_indd.svg
  packages/Atoms/Icon/assets/img/rpl_icon_tif.svg
  packages/Molecules/DocumentLink/DocumentLink.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#278 [SDPA-2017] Adds browser icon.
  packages/Atoms/Icon/assets/img/rpl_icon_browser.svg
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#285 Release/v1.0.0 alpha.63
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#288 [SDPA-776] Pagination width to match cards
  packages/Molecules/Search/SearchResults.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#286 [SDPA-1517] Insert quickexit into menu and remove from body if menu open
  packages/Molecules/Layout/PageLayout.vue
  packages/Molecules/Layout/index.js
  packages/Organisms/SiteHeader/index.vue
  packages/Organisms/SiteHeader/menu.vue
Labels: ready to be merged

#289 [SDPA-2187] Implement an interface for defining child column breakpoints
  packages/Atoms/Global/mixins/ProvideChildCols.js
  packages/Molecules/Card/no-ssr/CardCarousel.vue
  packages/Molecules/Card/stories.js
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#283 [SDPA-2131]Added default variables for rpl-markup and underlines in rpl-textlink
  packages/Atoms/Link/TextLink.vue
  packages/Organisms/Markup/Markup.vue
Labels: ready to be merged

#290 [SDPA-2188] Clicking an active (current path) link will reload the page.
  packages/Atoms/Link/Link.vue
Labels: ready for test

#295 Feature/1.0.0 alpha.64
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#291 [SDPA-1896] Fixed back to top style
  packages/Molecules/Layout/BackToTop.vue
Labels: ready to be merged

#296 [SDPA-2231] Add childColsBp to Search Results component.
  packages/Molecules/Search/SearchResults.vue
  src/storybook-components/EventSearchPage.vue
  src/storybook-components/GrantSearchPage.vue
  src/storybook-components/SearchPage.vue
  src/storybook-components/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#287 [SDPA-1658] Fix h2 top margin when there is something above it.
  packages/Organisms/Markup/Markup.vue
Labels: ready for test

#299 1.0.0 alpha.65
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#304 [SDPA-2252] Improved site section navi menu accessibility
  packages/Organisms/SiteSectionNavigation/menu.vue
Labels: ready to be merged

#305 [SDPA-2257] Added h1 element to sitemap page
  packages/Molecules/Sitemap/index.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#302 [SDPA-2273] Update Search Form features.
  packages/Molecules/Search/SearchForm.vue
  packages/Molecules/Search/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#301 [SDPA-2188] Added fix for Webkit browsers.
  packages/Atoms/Link/Link.vue
Labels: ready to be merged

#303 Add single select option to RplChecklist
  packages/Molecules/Form/fields/fieldRplchecklist.vue
  packages/Molecules/Form/package.json
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#309 [SDPA-2281] Allow spacing on pagination for back to top button.
  packages/Molecules/Search/SearchResults.vue
Labels: needs review

#311 1.0.0 alpha.66
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#313 Update vue-carousel deps
  package-lock.json
  packages/Molecules/Card/package.json
  packages/Organisms/ImageGallery/package.json
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test
