Repository dpc-sdp/ripple, pull requests merged in 2019-07, with the labels that each got.

#403 [SDPA-2712] Adds eslint config to monorepo
  .eslintignore
  .sass-lint.yml
  examples/vic-gov-au/.eslintrc.js
  package.json
  packages/ripple-nuxt-tide/lib/core/mapping-filters.js
  packages/ripple-nuxt-tide/lib/core/middleware-helper.js
  packages/ripple-nuxt-tide/lib/core/page-types.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  packages/ripple-nuxt-tide/modules/alert/localstorage.js
  packages/ripple-nuxt-tide/modules/alert/plugin.js
  packages/ripple-nuxt-tide/modules/authenticated-content/components/TideLogin.vue
  packages/ripple-nuxt-tide/modules/authenticated-content/pages/Login.vue
  packages/ripple-nuxt-tide/modules/authenticated-content/pages/Reset.vue
  packages/ripple-nuxt-tide/modules/event/mapping-filters.js
  packages/ripple-nuxt-tide/modules/event/pages/search.vue
  packages/ripple-nuxt-tide/modules/grant/pages/search.vue
  packages/ripple-nuxt-tide/modules/profile/pages/search.vue
  packages/ripple-nuxt-tide/modules/search/lib/search/services/elasticsearch/elasticsearch.js
  packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
  packages/ripple-nuxt-tide/modules/search/pages/TideSearch.vue
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
  packages/ripple-nuxt-tide/test/unit/anchorlinks.test.js
  packages/ripple-nuxt-tide/test/unit/tide.test.js
  packages/ripple-nuxt-ui/lib/module.js
  packages/ripple-ui-components/.eslintignore
  packages/ripple-ui-components/.eslintrc.js
  packages/ripple-ui-components/.sass-lint.yml
  packages/ripple-ui-components/components/Atoms/Global/mixins/breakpoint.js
  packages/ripple-ui-components/components/Atoms/Grid/index.js
  packages/ripple-ui-components/components/Atoms/Icon/TextIcon.vue
  packages/ripple-ui-components/components/Atoms/Icon/index.js
  packages/ripple-ui-components/components/Atoms/Link/TextLink.vue
  packages/ripple-ui-components/components/Atoms/Link/index.js
  packages/ripple-ui-components/components/Molecules/Card/CardContent.vue
  packages/ripple-ui-components/components/Molecules/Card/index.js
  packages/ripple-ui-components/components/Molecules/Card/mixins/cardtrimfield.js
  packages/ripple-ui-components/components/Molecules/Form/fields/fieldRplclearform.vue
  packages/ripple-ui-components/components/Molecules/Form/fields/fieldRplmarkup.vue
  packages/ripple-ui-components/components/Molecules/Form/index.vue
  packages/ripple-ui-components/components/Molecules/Layout/PageLayout.vue
  packages/ripple-ui-components/components/Molecules/Layout/index.js
  packages/ripple-ui-components/components/Molecules/Map/Map.vue
  packages/ripple-ui-components/components/Molecules/Search/SearchResults.vue
  packages/ripple-ui-components/components/Organisms/Event/index.js
  packages/ripple-ui-components/components/Organisms/HeroBanner/index.js
  packages/ripple-ui-components/components/Organisms/Markup/Markup.vue
  packages/ripple-ui-components/components/Organisms/News/index.js
  packages/ripple-ui-components/components/Organisms/Profile/ProfileHighlightHonourRoll.vue
  packages/ripple-ui-components/components/Organisms/Publication/PublicationAuthorInformation.vue
  packages/ripple-ui-components/src/storybook-components/_data/demoData.js
  packages/ripple-ui-components/src/storybook-components/scss/story.scss
  packages/ripple-ui-components/test/unit/helpers.test.js
  test/e2e/integration/Grants/SubmitAGrant/step_definition.js
  test/e2e/integration/Protected-content/ProtectedContent/step_definition.js
  test/e2e/integration/common/index.js
  test/e2e/plugins/index.js
  yarn.lock
Labels: needs review

#407 [SDPA-2705] Configure tests to run in circleci
  .circleci/config.yml
  examples/vic-gov-au/nuxt.config.js
  jest.config.js
  package.json
  packages/ripple-test-tools/tide-admin.js
Labels: needs review

#405 Added vicpol form redirect into core
  examples/vic-gov-au/components/MyButton.vue
  examples/vic-gov-au/pages/my-page.vue
  packages/ripple-nuxt-tide/lib/components/AppForm.vue
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
Labels: needs review

#409 Fix icons not rendering due to wrong path in ripple-nuxt-ui
  packages/ripple-nuxt-ui/lib/module.js
Labels: needs review

#406 [SDPA-2689] Store authentication token more securely.
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/lib/templates/plugin.js
  packages/ripple-nuxt-tide/modules/authenticated-content/components/TideLogin.vue
  packages/ripple-nuxt-tide/modules/authenticated-content/lib/authenticate.js
  packages/ripple-nuxt-tide/modules/authenticated-content/lib/preview.js
  packages/ripple-nuxt-tide/modules/authenticated-content/localstorage.js
  packages/ripple-nuxt-tide/modules/authenticated-content/module.js
  packages/ripple-nuxt-tide/modules/authenticated-content/pages/Login.vue
  packages/ripple-nuxt-tide/modules/authenticated-content/plugin.js
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-tide/test/unit/authenticated-content.test.js
  packages/ripple-test-tools/page-models.js
  packages/ripple-test-tools/tide-admin.js
  test/e2e/fixtures/Pages/LandingPage/draft.json
  test/e2e/integration/Preview-content/PreviewContent.feature
  test/e2e/integration/Preview-content/PreviewContent/step_definition.js
  test/e2e/integration/common/index.js
Labels: needs review

#413 [SDPSUP-485] Add honeypot to content rating form
  packages/ripple-nuxt-tide/lib/components/AppContentRating.vue
Labels: ready for test

#419 [SDPA-2715] Adds lint step on pre-push hook
  package.json
  yarn.lock
Labels: ready for test

#411 [SDPA-2498] Transcript to use HTML.
  packages/components/Molecules/EmbeddedVideo/index.vue
  packages/ripple-nuxt-tide/modules/media/components/EmbeddedVideo.vue
Labels: ready to be merged

#414 [SDPA-2833] Update webform conditional.
  packages/ripple-nuxt-tide/lib/components/AppForm.vue
  packages/ripple-nuxt-tide/modules/webform/conditional-logic.js
  packages/ripple-nuxt-tide/test/unit/webform.test.js
Labels: ready for test

#421 [SDPA-2549] Wrapping tweak to content rating radio buttons.
  packages/ripple-nuxt-tide/lib/components/AppContentRating.vue
Labels: ready for test

#418 [SDPA-2651] Improve publication body and sidebar top alignment.
  packages/components/Molecules/DescriptionList/DescriptionList.vue
  packages/ripple-nuxt-tide/modules/publication/pages/index.vue
Labels: ready to be merged

#429 [SDPA-2747] Event page e2e test
  packages/ripple-test-tools/index.js
  packages/ripple-test-tools/page-models.js
  packages/ripple-test-tools/tide-admin.js
  packages/ripple-test-tools/util.js
  test/e2e/fixtures/Pages/Event/event.json
  test/e2e/integration/Events/Events.feature
  test/e2e/integration/Events/Events/hooks.js
  test/e2e/integration/Events/Events/step_definition.js
  test/e2e/integration/common/index.js
Labels: needs review

#427 [SDPA-2862] Removed vic gov au app from Ripple
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/lib/pages/sdp-apps/UrlShorten.vue
Labels: ready for test

#424 Add back custom component loader
  examples/vic-gov-au/tide/tide.load-components.js
  packages/ripple-nuxt-tide/lib/core/componentLoader.js
Labels: ready to be merged

#420 Adds Circle CI config for regression tests
  .circleci/config.yml
  package.json
  packages/ripple-test-tools/package.json
  test/e2e/integration/Homepage/Homepage.feature
  test/e2e/integration/LandingPage/LandingPage.feature
  test/e2e/integration/Preview-content/PreviewContent.feature
  test/e2e/integration/Protected-content/ProtectedContent.feature
  test/e2e/plugins/index.js
Labels: ready for test

#434 Release/1.0.0 beta.7
  examples/vic-gov-au/package.json
  lerna.json
  packages/components/Atoms/Button/package.json
  packages/components/Atoms/Global/package.json
  packages/components/Atoms/Grid/package.json
  packages/components/Atoms/Icon/package.json
  packages/components/Atoms/Link/package.json
  packages/components/Atoms/MetaTag/package.json
  packages/components/Molecules/Alert/package.json
  packages/components/Molecules/AnchorLinks/package.json
  packages/components/Molecules/Breadcrumbs/package.json
  packages/components/Molecules/Card/package.json
  packages/components/Molecules/Contact/package.json
  packages/components/Molecules/DescriptionList/package.json
  packages/components/Molecules/DocumentLink/package.json
  packages/components/Molecules/EmbeddedVideo/package.json
  packages/components/Molecules/Figure/package.json
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Layout/package.json
  packages/components/Molecules/List/package.json
  packages/components/Molecules/Map/package.json
  packages/components/Molecules/Pagination/package.json
  packages/components/Molecules/PublishDateAndAuthor/package.json
  packages/components/Molecules/RelatedLinks/package.json
  packages/components/Molecules/Search/package.json
  packages/components/Molecules/ShareThis/package.json
  packages/components/Molecules/Sitemap/package.json
  packages/components/Molecules/Timeline/package.json
  packages/components/Molecules/WhatsNext/package.json
  packages/components/Organisms/Accordion/package.json
  packages/components/Organisms/CallToAction/package.json
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignSecondary/package.json
  packages/components/Organisms/Event/package.json
  packages/components/Organisms/Grants/package.json
  packages/components/Organisms/HeroBanner/package.json
  packages/components/Organisms/ImageGallery/package.json
  packages/components/Organisms/Markup/package.json
  packages/components/Organisms/News/package.json
  packages/components/Organisms/Profile/package.json
  packages/components/Organisms/Publication/package.json
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteHeader/package.json
  packages/components/Organisms/SiteSectionNavigation/package.json
  packages/components/Organisms/UpdatedDate/package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  src/package.json
Labels: ready to be merged

#435 fix for svgloader adding duplicate config
  packages/ripple-nuxt-ui/lib/module.js
  packages/ripple-nuxt-ui/package.json
  yarn.lock
Labels: needs review

#417 [SDPA-2730] Publication Image - if no caption, then title always shows.
  packages/components/Organisms/ImageGallery/FullscreenImage.vue
Labels: ready for test

#412 [SDPA-2718] Update docs / new-component / package-dependencies scripts.
  package.json
  src/package.json
  src/scripts/generate-component/.npmignore
  src/scripts/generate-component/LICENSE
  src/scripts/generate-component/component_template.vue
  src/scripts/generate-component/generate-component.js
  src/scripts/generate-component/index_template.js
  src/scripts/generate-component/package_template.json
  src/scripts/generate-component/stories_template.js
  src/scripts/generate-dependencies/dependency-utils.js
  src/scripts/generate-dependencies/generate-dependencies.js
  src/scripts/generate-package/generate-package.js
  src/scripts/generate-package/index_template.js
  src/scripts/generate-package/package_template.json
  src/scripts/generate-package/stories_template.js
  src/scripts/generate-readme/generate-readme.js
  yarn.lock
Labels: ready to be merged

#425 [SDPA-2857] Add interface to extend markup plugins.
  examples/vic-gov-au/tide/tide.markup-plugins.js
  packages/ripple-nuxt-tide/lib/config/markup-plugins.js
  packages/ripple-nuxt-tide/lib/core/markup-plugins-loader.js
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/test/unit/markup-transpiler.test.js
Labels: needs review

#438 [SDPA-2906] Fix commented out alerts import
  packages/ripple-nuxt-tide/lib/layouts/default.vue
Labels: ready for test

#441 [SDPA-2918] Cleanup and document example nuxt.config
  examples/vic-gov-au/example.env
  examples/vic-gov-au/nuxt.config.js
  examples/vic-gov-au/package.json
  packages/components/Atoms/Global/README.md
  packages/ripple-nuxt-tide/lib/core/basic-auth.js
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/lib/module.js
  packages/ripple-nuxt-ui/package.json
Labels: ready to be merged

#443 v1.0.0-beta.9
  examples/vic-gov-au/package.json
  lerna.json
  packages/components/Atoms/Button/package.json
  packages/components/Atoms/Global/package.json
  packages/components/Atoms/Grid/package.json
  packages/components/Atoms/Icon/package.json
  packages/components/Atoms/Link/package.json
  packages/components/Atoms/MetaTag/package.json
  packages/components/Molecules/Alert/package.json
  packages/components/Molecules/AnchorLinks/package.json
  packages/components/Molecules/Breadcrumbs/package.json
  packages/components/Molecules/Card/package.json
  packages/components/Molecules/Contact/package.json
  packages/components/Molecules/DescriptionList/package.json
  packages/components/Molecules/DocumentLink/package.json
  packages/components/Molecules/EmbeddedVideo/package.json
  packages/components/Molecules/Figure/package.json
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Layout/package.json
  packages/components/Molecules/List/package.json
  packages/components/Molecules/Map/package.json
  packages/components/Molecules/Pagination/package.json
  packages/components/Molecules/PublishDateAndAuthor/package.json
  packages/components/Molecules/RelatedLinks/package.json
  packages/components/Molecules/Search/package.json
  packages/components/Molecules/ShareThis/package.json
  packages/components/Molecules/Sitemap/package.json
  packages/components/Molecules/Timeline/package.json
  packages/components/Molecules/WhatsNext/package.json
  packages/components/Organisms/Accordion/package.json
  packages/components/Organisms/CallToAction/package.json
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignSecondary/package.json
  packages/components/Organisms/Event/package.json
  packages/components/Organisms/Grants/package.json
  packages/components/Organisms/HeroBanner/package.json
  packages/components/Organisms/ImageGallery/package.json
  packages/components/Organisms/Markup/package.json
  packages/components/Organisms/News/package.json
  packages/components/Organisms/Profile/package.json
  packages/components/Organisms/Publication/package.json
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteHeader/package.json
  packages/components/Organisms/SiteSectionNavigation/package.json
  packages/components/Organisms/UpdatedDate/package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  src/package.json
Labels: needs review

#444 [SDPA-1948] Add unit tests for grants utils.
  packages/ripple-nuxt-tide/modules/grant/lib/utils.js
  packages/ripple-nuxt-tide/test/unit/grant-utilities.test.js
Labels: ready to be merged

#451 [SDPA-1166] Form alerts.
  packages/components/Molecules/Form/formAlert.vue
  packages/components/Molecules/Form/index.vue
  packages/components/Molecules/Form/stories.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#452 [SDPA-2934] Fix short campaign secondary text causing button wrapping.
  packages/components/Organisms/CampaignSecondary/index.vue
Labels: ready to be merged

#450 [SDPA-2945] Prevent underline from showing after the icon on a text link.
  packages/components/Atoms/Icon/TextIcon.vue
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#455 Don't run tests that aren't supported by the demo landing page.
  test/e2e/integration/LandingPage/DemoLandingPage.feature
Labels: needs review

#442 [SDPA-2911] Update Readme
  README.md
  docs/logo.png
Labels: ready to be merged

#445 [SDPA-2928] Generate docs with custom text.
  packages/components/Atoms/Button/README.md
  packages/components/Atoms/Global/README.md
  packages/components/Atoms/Grid/README.md
  packages/components/Atoms/Icon/README.md
  packages/components/Atoms/Link/README.md
  packages/components/Atoms/MetaTag/README.md
  packages/components/Molecules/Alert/README.md
  packages/components/Molecules/AnchorLinks/README.md
  packages/components/Molecules/Breadcrumbs/README.md
  packages/components/Molecules/Card/README.md
  packages/components/Molecules/Contact/README.md
  packages/components/Molecules/DescriptionList/README.md
  packages/components/Molecules/DocumentLink/README.md
  packages/components/Molecules/EmbeddedVideo/README.md
  packages/components/Molecules/Figure/README.md
  packages/components/Molecules/Form/README.md
  packages/components/Molecules/Layout/README.md
  packages/components/Molecules/List/README.md
  packages/components/Molecules/Map/README.md
  packages/components/Molecules/Pagination/README.md
  packages/components/Molecules/PublishDateAndAuthor/README.md
  packages/components/Molecules/RelatedLinks/README.md
  packages/components/Molecules/Search/README.md
  packages/components/Molecules/ShareThis/README.md
  packages/components/Molecules/Sitemap/README.md
  packages/components/Molecules/Timeline/README.md
  packages/components/Molecules/WhatsNext/README.md
  packages/components/Organisms/Accordion/README.md
  packages/components/Organisms/CallToAction/README.md
  packages/components/Organisms/CampaignPrimary/README.md
  packages/components/Organisms/CampaignSecondary/README.md
  packages/components/Organisms/Event/README.md
  packages/components/Organisms/Grants/README.md
  packages/components/Organisms/HeroBanner/README.md
  packages/components/Organisms/ImageGallery/README.md
  packages/components/Organisms/Markup/README.md
  packages/components/Organisms/News/README.md
  packages/components/Organisms/Profile/README.md
  packages/components/Organisms/Publication/README.md
  packages/components/Organisms/SiteFooter/README.md
  packages/components/Organisms/SiteHeader/README.md
  packages/components/Organisms/SiteSectionNavigation/README.md
  packages/components/Organisms/UpdatedDate/README.md
  src/scripts/generate-readme/README_template.md
  src/scripts/generate-readme/generate-readme.js
  src/scripts/generate-readme/template_dependency_graph.md
  src/scripts/generate-readme/template_description.md
  src/scripts/generate-readme/template_import.md
  src/scripts/generate-readme/template_install.md
  src/scripts/generate-readme/template_license.md
  src/scripts/generate-readme/template_title.md
  src/scripts/generate-readme/template_usage_and_tests.md
Labels: ready to be merged

#453 [SDPA-2950] Fix: Middleware to load sequentially.
  packages/ripple-nuxt-tide/lib/core/middleware-helper.js
Labels: ready to be merged

#456 Added missing auth token
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/templates/plugin.js
Labels: ready for test

#426 FV map
  packages/components/Molecules/Map/package.json
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapCard.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapCategoriesPage.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapExpandButton.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapPreventionFamilyViolence.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapProjectCard.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapProjectDetails.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapSidebarHeader.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapSidebarHome.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/helper.js
  yarn.lock
Labels: ready to be merged

#432 Add unit tests for authenticated content setServerToken
  packages/ripple-nuxt-tide/modules/authenticated-content/lib/authenticate.js
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-tide/test/unit/authenticate.test.js
  yarn.lock
Labels: ready to be merged
