Repository dpc-sdp/ripple, pull requests merged in 2019-06, with the labels that each got.

#380 [SDPA-2629] Remove breakpoint mixin for pagination and set padding
  package-lock.json
  packages/Molecules/Layout/PageLayout.vue
  packages/Molecules/Pagination/index.vue
  packages/Molecules/Search/SearchResults.vue
  packages/Organisms/Markup/stories.js
  src/storybook-components/EventSearchPage.vue
  src/storybook-components/GrantSearchPage.vue
  src/storybook-components/SearchPage.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#381 [SDPA-2613] Change publication info date format to month and year.
  packages/Organisms/Publication/PublicationAuthorInformation.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#383 Release/v1.0.0 alpha.81
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DescriptionList/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#377 Documentation script update.
  scripts/generate-readme/README_template.md
  scripts/generate-readme/generate-readme.js
  scripts/generate-readme/get-imports.js
Labels: ready to be merged

#382 [SDPA-2625] Fix border gradient in safari.
  packages/Molecules/AnchorLinks/index.vue
Labels: ready for test

#385 [SDPA-2643] Fixed invalid css selector error
  packages/Atoms/Global/mixins/deprecate.js
  packages/Molecules/Form/__tests__/fieldRplSelect.test.js
  packages/Molecules/Form/fields/fieldRplchecklist.vue
  packages/Molecules/Form/fields/fieldRplselect.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#386 [SDPA-2649] Fix select after clear form.
  packages/Molecules/Form/fields/fieldRplselect.vue
Labels: ready for test

#387 Release/1.0.0 alpha.82
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DescriptionList/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#389 [SDPA-2675] Adds default values for publication image labels.
  packages/Organisms/Publication/PublicationImage.vue
Labels: needs review

#390 Release/v1.0.0 alpha.83
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DescriptionList/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#391 [SDPA-2632] Featured Nav improvements.
  packages/Molecules/Card/CardNavigationFeatured.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#392 Feature/1.0.0 alpha.84
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/README.md
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/README.md
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DescriptionList/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/README.md
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/Publication/README.md
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#399 Added readme for beta
  README.md
Labels: needs review

#400 [SDPA-2776] Lerna update
  .env
  .gitignore
  examples/vic-gov-au/.env
  examples/vic-gov-au/package.json
  examples/vic-gov-au/pages/README.md
  examples/vic-gov-au/plugins/README.md
  lerna.json
  package-lock.json
  package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-ui-components/components/Atoms/Button/package.json
  packages/ripple-ui-components/components/Atoms/Global/package.json
  packages/ripple-ui-components/components/Atoms/Grid/package.json
  packages/ripple-ui-components/components/Atoms/Icon/package.json
  packages/ripple-ui-components/components/Atoms/Link/package.json
  packages/ripple-ui-components/components/Atoms/MetaTag/package.json
  packages/ripple-ui-components/components/Molecules/Alert/package.json
  packages/ripple-ui-components/components/Molecules/AnchorLinks/package.json
  packages/ripple-ui-components/components/Molecules/Breadcrumbs/package.json
  packages/ripple-ui-components/components/Molecules/Card/package.json
  packages/ripple-ui-components/components/Molecules/Contact/package.json
  packages/ripple-ui-components/components/Molecules/DescriptionList/package.json
  packages/ripple-ui-components/components/Molecules/DocumentLink/package.json
  packages/ripple-ui-components/components/Molecules/EmbeddedVideo/package.json
  packages/ripple-ui-components/components/Molecules/Figure/package.json
  packages/ripple-ui-components/components/Molecules/Form/package.json
  packages/ripple-ui-components/components/Molecules/Layout/package.json
  packages/ripple-ui-components/components/Molecules/List/package.json
  packages/ripple-ui-components/components/Molecules/Map/package.json
  packages/ripple-ui-components/components/Molecules/Pagination/package.json
  packages/ripple-ui-components/components/Molecules/PublishDateAndAuthor/package.json
  packages/ripple-ui-components/components/Molecules/RelatedLinks/package.json
  packages/ripple-ui-components/components/Molecules/Search/package.json
  packages/ripple-ui-components/components/Molecules/ShareThis/package.json
  packages/ripple-ui-components/components/Molecules/Sitemap/package.json
  packages/ripple-ui-components/components/Molecules/Timeline/package.json
  packages/ripple-ui-components/components/Molecules/WhatsNext/package.json
  packages/ripple-ui-components/components/Organisms/Accordion/package.json
  packages/ripple-ui-components/components/Organisms/CallToAction/package.json
  packages/ripple-ui-components/components/Organisms/CampaignPrimary/package.json
  packages/ripple-ui-components/components/Organisms/CampaignSecondary/package.json
  packages/ripple-ui-components/components/Organisms/Event/package.json
  packages/ripple-ui-components/components/Organisms/Grants/package.json
  packages/ripple-ui-components/components/Organisms/HeroBanner/package.json
  packages/ripple-ui-components/components/Organisms/ImageGallery/package.json
  packages/ripple-ui-components/components/Organisms/Markup/package.json
  packages/ripple-ui-components/components/Organisms/News/package.json
  packages/ripple-ui-components/components/Organisms/Profile/package.json
  packages/ripple-ui-components/components/Organisms/Publication/package.json
  packages/ripple-ui-components/components/Organisms/SiteFooter/package.json
  packages/ripple-ui-components/components/Organisms/SiteHeader/package.json
  packages/ripple-ui-components/components/Organisms/SiteSectionNavigation/package.json
  packages/ripple-ui-components/components/Organisms/UpdatedDate/package.json
  packages/ripple-ui-components/package.json
  yarn.lock
Labels: needs review

#404 [SDPA-1482] Adding support for windows cmd on example.
  README.md
  examples/vic-gov-au/package.json
  yarn.lock
Labels: needs review
