Repository dpc-sdp/ripple, pull requests merged in 2019-04, with the labels that each got.

#308 Fix sass lint issue in rpl-image-gallery
  packages/Organisms/ImageGallery/ImageGallery.vue
Labels: needs review

#314 Fix for masonry layout importing either amd or es module
  packages/Organisms/SiteFooter/FooterNavigation.vue
Labels: ready to be merged

#306 [SDPA-1957] Makes form alert reactive to variant prop.
  packages/Molecules/Form/formAlert.vue
Labels: ready for test

#320 [SDPA-2329] Add key to search result
  packages/Molecules/Search/SearchResults.vue
Labels: needs review

#319 [SDPA-2230] IE11 menu wrap
  packages/Organisms/SiteHeader/index.vue
  packages/Organisms/SiteHeader/menu.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#322 [SDPA-1941] Use forked version of vue-social-sharing to fix IE issue.
  package-lock.json
  packages/Molecules/ShareThis/package.json
Labels: ready for test

#326 [SDPA-2375] Fix issue where quick exit was appearing for each menu level
  packages/Organisms/SiteHeader/menu.vue
Labels: needs review

#293 [SDPA-1584] Adds semantic markup for Share This.
  packages/Molecules/ShareThis/index.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#312 [SDPA-1607] Adds alert slot above header in page layout.
  packages/Molecules/Alert/Alert.vue
  packages/Molecules/Layout/BaseLayout.vue
  src/storybook-components/Page.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#307 [SDPA-1604] Adds better screen reader support for pagination.
  packages/Molecules/Pagination/index.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#331 [SDPA-2420] Fix empty a href tags causing sorry! page
  packages/Atoms/Icon/TextIcon.vue
Labels: ready to be merged

#321 [SDPA-2341] Move wysiwyg styles into RplMarkup
  package-lock.json
  packages/Molecules/EmbeddedVideo/index.vue
  packages/Organisms/Markup/Markup.vue
  packages/Organisms/Markup/examplePlugins.js
  packages/Organisms/Markup/scss/_iframe.scss
  packages/Organisms/Markup/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#334 [SDPA-2437] Fix image gallery height in modal.
  packages/Organisms/ImageGallery/ImageGallery.vue
Labels: needs review

#167 [WMV-1244] Added a Map component to Ripple.
  .storybook/webpack.config.js
  jest.config.js
  package-lock.json
  package.json
  packages/Atoms/Icon/stories.js
  packages/Molecules/Map/.npmignore
  packages/Molecules/Map/CloseButton.vue
  packages/Molecules/Map/LICENSE
  packages/Molecules/Map/Map.vue
  packages/Molecules/Map/MapIndicator.vue
  packages/Molecules/Map/README.md
  packages/Molecules/Map/index.js
  packages/Molecules/Map/lib/ol.js
  packages/Molecules/Map/package.json
  packages/Molecules/Map/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: Requires more work

#336 Fix for link inner - to display as inline.
  packages/Atoms/Link/Link.vue
  packages/Molecules/Card/CardContent.vue
  packages/Molecules/Card/CardNavigationFeatured.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#292 [SDPA-2221] Re implements Rpl-select with focus on accessibility
  packages/Atoms/Global/mixins/clickoutside.js
  packages/Molecules/Form/Checkbox.vue
  packages/Molecules/Form/__tests__/fieldRplSelect.test.js
  packages/Molecules/Form/fields/fieldRplselect.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#310 [SDPA-1585] Add alt text to campaign primary image
  packages/Organisms/CampaignPrimary/index.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test
