Repository dpc-sdp/ripple, pull requests merged in 2019-09, with the labels that each got.

#440 [SDPA-2909] Add custom theme documentation.
  packages/ripple-nuxt-tide/README.md
  packages/ripple-nuxt-ui/README.md
Labels: needs review

#505 [SDPA-3140] Moves Sitemap to ripple nuxt-tide
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/lib/pages/Sitemap.vue
Labels: ready to be merged

#508 [SDPA-3128] Added property to exclude hits.
  packages/ripple-nuxt-tide/modules/search/lib/search/module.js
  packages/ripple-nuxt-tide/modules/search/lib/search/services/elasticsearch/lib/api.js
  packages/ripple-nuxt-tide/modules/search/lib/search/services/elasticsearch/lib/querybuilder.js
  packages/ripple-nuxt-tide/modules/search/pages/TideSearch.vue
Labels: ready for test

#514 Add !default to $rpl-section-menu-background-color to make overridable.
  packages/components/Organisms/SiteSectionNavigation/index.vue
Labels: ready for test

#511 [SDPA-3161] Removed old IE tracking function call. Threw an error.
  packages/ripple-nuxt-tide/lib/core/tracking.js
Labels: ready for test

#513 [SDPA-3043] Add text field limits.
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
Labels: needs review

#510 [SDPA-3144] Footer mobile navigation tweaks:
  packages/components/Organisms/SiteFooter/FooterNavigation.vue
  packages/components/Organisms/SiteFooter/SiteFooter.vue
Labels: ready to be merged

#517 [SDPA-3043] Add field limit to Content Rating.
  packages/ripple-nuxt-tide/lib/components/AppContentRating.vue
Labels: ready for test

#516 [SDPA-3048] Primary campaign caption
  packages/components/Molecules/Card/README.md
  packages/components/Molecules/Layout/README.md
  packages/components/Molecules/Layout/package.json
  packages/components/Organisms/CampaignPrimary/CampaignPrimaryImage.vue
  packages/components/Organisms/CampaignPrimary/README.md
  packages/components/Organisms/CampaignPrimary/index.vue
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignPrimary/stories.js
  packages/components/Organisms/Grants/README.md
  packages/components/Organisms/SiteFooter/README.md
  packages/ripple-nuxt-tide/lib/config/tide.config.js
  packages/ripple-nuxt-tide/lib/core/mapping-filters.js
  packages/ripple-nuxt-tide/lib/core/middleware.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#518 [SDPA-3046] Hero banner caption
  packages/components/Organisms/SiteFooter/SiteFooter.vue
  packages/components/Organisms/SiteFooter/stories.js
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/lib/templates/plugin.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#502 [SDPA-3122] Date filter fix.
  packages/ripple-nuxt-tide/modules/event/formdata.js
  packages/ripple-nuxt-tide/modules/event/pages/search.vue
Labels: ready for test

#520 [SDPA-3087] Provide fallback images for social media.
  examples/vic-gov-au/static/img/social-media-image.jpg
  packages/ripple-nuxt-tide/lib/config/tide.config.js
  packages/ripple-nuxt-tide/lib/core/middleware.js
Labels: needs review

#524 Release/v1.2.0
  examples/basic-examples/package.json
  examples/vic-gov-au/package.json
  lerna.json
  packages/components/Atoms/Button/package.json
  packages/components/Atoms/Global/package.json
  packages/components/Atoms/Grid/package.json
  packages/components/Atoms/Icon/package.json
  packages/components/Atoms/Link/package.json
  packages/components/Atoms/MetaTag/package.json
  packages/components/Molecules/Alert/package.json
  packages/components/Molecules/AnchorLinks/package.json
  packages/components/Molecules/Breadcrumbs/package.json
  packages/components/Molecules/Card/package.json
  packages/components/Molecules/Contact/package.json
  packages/components/Molecules/DescriptionList/package.json
  packages/components/Molecules/DocumentLink/package.json
  packages/components/Molecules/EmbeddedVideo/package.json
  packages/components/Molecules/Figure/package.json
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Layout/package.json
  packages/components/Molecules/List/package.json
  packages/components/Molecules/Map/package.json
  packages/components/Molecules/Pagination/package.json
  packages/components/Molecules/PublishDateAndAuthor/package.json
  packages/components/Molecules/RelatedLinks/package.json
  packages/components/Molecules/Search/package.json
  packages/components/Molecules/ShareThis/package.json
  packages/components/Molecules/Sitemap/package.json
  packages/components/Molecules/Timeline/package.json
  packages/components/Molecules/WhatsNext/package.json
  packages/components/Organisms/Accordion/package.json
  packages/components/Organisms/CallToAction/package.json
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignSecondary/package.json
  packages/components/Organisms/Event/package.json
  packages/components/Organisms/Grants/package.json
  packages/components/Organisms/HeroBanner/package.json
  packages/components/Organisms/ImageGallery/package.json
  packages/components/Organisms/Markup/package.json
  packages/components/Organisms/News/package.json
  packages/components/Organisms/Profile/package.json
  packages/components/Organisms/Publication/package.json
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteHeader/package.json
  packages/components/Organisms/SiteSectionNavigation/package.json
  packages/components/Organisms/UpdatedDate/package.json
  packages/create-ripple-app/package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  src/package.json
  yarn.lock
Labels: needs review

#527 [SDPA-3163] CardKeydates truncate text to fit in the card
  packages/components/Atoms/Global/utils/helpers.js
  packages/components/Molecules/Card/CardKeydates.vue
  packages/components/Molecules/Card/__test__/cardKeydates.test.js
  packages/ripple-nuxt-tide/lib/core/tide-helper.js
  packages/ripple-nuxt-tide/modules/publication/pages/index.vue
  packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
Labels: ready for test

#534 [SDPA-2705] Turn on regression tests on for release branches and nightly
  .circleci/config.yml
  .gitignore
  examples/basic-examples/package.json
  examples/basic-examples/test/e2e/integration/custom/error-page.feature
  examples/basic-examples/test/e2e/integration/custom/error-page/step_definition.js
  examples/basic-examples/test/e2e/integration/custom/middleware.feature
  examples/basic-examples/test/e2e/integration/custom/middleware/step_definition.js
  examples/basic-examples/test/e2e/integration/custom/theming.feature
  examples/basic-examples/test/e2e/integration/custom/theming/step_definition.js
  examples/vic-gov-au/package.json
  package.json
  packages/ripple-test-tools/package.json
  scripts/cucumberconvertor.js
  yarn.lock
Labels: ready for test

#537 [SDPA-3250] Fix broken head if sitesection doesn't exist
  packages/ripple-nuxt-tide/lib/core/middleware.js
Labels: needs review, ready to be merged

#529 [SDPA-3117] Fixes to anchor link.
  examples/vic-gov-au/test/e2e/fixtures/page/anchorlinktest.yml
  examples/vic-gov-au/test/e2e/integration/core-modules/landingPage/AnchorLink.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/landingPage/AnchorLink/step_definition.js
  packages/components/Atoms/Global/utils/helpers.js
  packages/components/Organisms/Accordion/Accordion.vue
  packages/ripple-nuxt-tide/lib/config/markup-plugins.js
  packages/ripple-nuxt-tide/lib/core/anchorlinks.js
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  packages/ripple-nuxt-tide/test/unit/anchorlinks.test.js
  packages/ripple-test-tools/step_definitions/common/navigation.js
  src/test/unit/helpers.test.js
  test/e2e/integration/LandingPage/AnchorLink.feature
Labels: Requires more work, ready to be merged

#542 Release/v1.2.1
  .circleci/config.yml
  CHANGELOG.md
  examples/basic-examples/package.json
  examples/vic-gov-au/package.json
  lerna.json
  package.json
  packages/components/Atoms/Button/package.json
  packages/components/Atoms/Global/package.json
  packages/components/Atoms/Grid/package.json
  packages/components/Atoms/Icon/package.json
  packages/components/Atoms/Link/package.json
  packages/components/Atoms/MetaTag/package.json
  packages/components/Molecules/Alert/package.json
  packages/components/Molecules/AnchorLinks/package.json
  packages/components/Molecules/Breadcrumbs/package.json
  packages/components/Molecules/Card/package.json
  packages/components/Molecules/Contact/package.json
  packages/components/Molecules/DescriptionList/package.json
  packages/components/Molecules/DocumentLink/package.json
  packages/components/Molecules/EmbeddedVideo/package.json
  packages/components/Molecules/Figure/package.json
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Layout/package.json
  packages/components/Molecules/List/package.json
  packages/components/Molecules/Map/package.json
  packages/components/Molecules/Pagination/package.json
  packages/components/Molecules/PublishDateAndAuthor/package.json
  packages/components/Molecules/RelatedLinks/package.json
  packages/components/Molecules/Search/package.json
  packages/components/Molecules/ShareThis/package.json
  packages/components/Molecules/Sitemap/package.json
  packages/components/Molecules/Timeline/package.json
  packages/components/Molecules/WhatsNext/package.json
  packages/components/Organisms/Accordion/package.json
  packages/components/Organisms/CallToAction/package.json
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignSecondary/package.json
  packages/components/Organisms/Event/package.json
  packages/components/Organisms/Grants/package.json
  packages/components/Organisms/HeroBanner/package.json
  packages/components/Organisms/ImageGallery/package.json
  packages/components/Organisms/Markup/package.json
  packages/components/Organisms/News/package.json
  packages/components/Organisms/Profile/package.json
  packages/components/Organisms/Publication/package.json
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteHeader/package.json
  packages/components/Organisms/SiteSectionNavigation/package.json
  packages/components/Organisms/UpdatedDate/package.json
  packages/create-ripple-app/package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  src/package.json
Labels: ready to be merged

#546 Remove test for CRA update which modifies mock file.
  packages/create-ripple-app/__tests__/v18.test.js
Labels: ready to be merged

#533 [SDPA-3101] Update width to 100% to correctly fit 25% + 75% split.
  jest.config.js
  packages/components/Atoms/Global/scss/tools/_grid.scss
  packages/components/Atoms/Grid/grid.stories.mdx
  packages/components/Atoms/Grid/stories.js
  packages/create-ripple-app/__tests__/__mocks__/v18/package.json
  src/.storybook/addons.js
  src/.storybook/config.js
  src/.storybook/presets.js
  src/package.json
  src/storybook-components/scss/story.scss
  src/test/__snapshots__/storyshots.test.js.snap
  yarn.lock
Labels: ready to be merged

#538 [SDPA-2346] Added quick-exit button for search component.
  packages/components/Organisms/SiteHeader/search.vue
Labels: ready for test

#539 [SDPA-3216] CTA description fix for special characters
  packages/ripple-nuxt-tide/lib/core/html-utilities.js
  packages/ripple-nuxt-tide/lib/core/mapping-filters.js
  packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
  packages/ripple-nuxt-tide/test/unit/html-utilities.test.js
Labels: ready for test

#540 [SDPA-3269] Updated content rating form comment field
  packages/ripple-nuxt-tide/lib/components/AppContentRating.vue
Labels: ready for test

#544 [SDPA-936] Updated Content rating form buttons width for small screen.
  packages/ripple-nuxt-tide/lib/components/AppContentRating.vue
Labels: ready for test
