Repository dpc-sdp/ripple, pull requests merged in 2019-08, with the labels that each got.

#463 [SDPSUP-500] Fixed anchor link not working in SSR
  cypress.json
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  test/e2e/integration/LandingPage/AnchorLink.feature
  test/e2e/integration/LandingPage/AnchorLink/step_definition.js
Labels: ready to be merged

#447 [SDPA-2931] Adds default value to radios in webforms
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
Labels: ready to be merged

#482 [SDPSUP-668] Ignore null cookie for auth content.
  packages/ripple-nuxt-tide/modules/authenticated-content/lib/authenticate.js
Labels: URGENT, needs review

#468 [SDPA-2937] Acknowledgement flags
  packages/components/Organisms/SiteFooter/Acknowledgement.vue
  packages/components/Organisms/SiteFooter/SiteFooter.vue
  packages/components/Organisms/SiteFooter/assets/images/aboriginal-flag.png
  packages/components/Organisms/SiteFooter/assets/images/torres-strait-islander-flag.png
  packages/components/Organisms/SiteFooter/index.js
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteFooter/stories.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#485 [SDPA-2985] Prominent acknowledgment message.
  packages/components/Organisms/SiteFooter/Acknowledgement.vue
  packages/components/Organisms/SiteFooter/stories.js
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#384 [SDPA-2723] Add link target="" support to components that display menus.
  packages/components/Atoms/Global/mixins/parentlinks.js
  packages/components/Molecules/Sitemap/SitemapMenu.vue
  packages/components/Organisms/SiteFooter/FooterNavigation.vue
  packages/components/Organisms/SiteFooter/LinksAndCopyright.vue
  packages/components/Organisms/SiteHeader/menu.vue
  packages/components/Organisms/SiteSectionNavigation/menu.vue
Labels: ready to be merged

#454 [SDPA-2661] Increase RplList line-height from 14px to 16px.
  packages/components/Molecules/List/index.vue
Labels: ready for test

#458 [SDPA-2894] Adds fallback meta description if metatag.description is …
  packages/ripple-nuxt-tide/lib/core/middleware.js
Labels: ready for test

#464 [SDPA-2451] Adds additional status messages for grants.
  jest.config.js
  package.json
  packages/components/Molecules/List/index.vue
  packages/components/Organisms/Grants/GrantsOverview.vue
  packages/components/Organisms/Grants/__tests__/grantsoverview.test.js
  packages/components/Organisms/Grants/stories.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#473 [SDPA-1407] Make success icon the same size as close on grants overview
  packages/components/Organisms/Grants/GrantsOverview.vue
Labels: ready to be merged

#480 [SDPA-3007] Added winston as logger
  Dockerfile.app
  examples/vic-gov-au/store/index.js
  packages/ripple-nuxt-tide/lib/core/component-loader.js
  packages/ripple-nuxt-tide/lib/core/config-loader.js
  packages/ripple-nuxt-tide/lib/core/index.js
  packages/ripple-nuxt-tide/lib/core/logger.js
  packages/ripple-nuxt-tide/lib/core/markup-plugins-loader.js
  packages/ripple-nuxt-tide/lib/core/middleware-helper.js
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/core/page-types.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/lib/server-middleware/logger.js
  packages/ripple-nuxt-tide/lib/templates/plugin.js
  packages/ripple-nuxt-tide/modules/alert/plugin.js
  packages/ripple-nuxt-tide/modules/authenticated-content/pages/Reset.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapExpandButton.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapPreventionFamilyViolence.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/lib/fetch-external-data.js
  packages/ripple-nuxt-tide/modules/event/mapping-filters.js
  packages/ripple-nuxt-tide/modules/gtm/templates/plugin.js
  packages/ripple-nuxt-tide/modules/landing-page/mapping-filters.js
  packages/ripple-nuxt-tide/modules/search/lib/search/module.js
  packages/ripple-nuxt-tide/modules/webform/conditional-logic.js
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
  packages/ripple-nuxt-tide/package.json
  yarn.lock
Labels: ready for test

#466 [SDPA-2983] Links default to opening in the same window
  packages/components/Atoms/Global/README.md
  packages/components/Atoms/Global/index.js
  packages/components/Atoms/Link/Link.vue
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#474 [SDPA-2432] Use path instead of fullpath for route query
  packages/ripple-nuxt-tide/lib/core/middleware.js
Labels: ready to be merged

#491 [SDPA-3061] fix vue warning on Rpl-List
  packages/components/Molecules/List/index.vue
Labels: ready for test

#478 [SDPA-2594] Hero Banner background position.
  packages/components/Molecules/Layout/PageLayout.vue
  packages/components/Organisms/HeroBanner/HeroBanner.vue
Labels: ready to be merged

#490 Feature/graceful shutdown
  Dockerfile.app
Labels: ready for test

#481 [SDPA-1408] Provide more precise scaling options for icons.
  packages/components/Organisms/Grants/GrantsOverview.vue
Labels: ready for test

#479 [SDPA-910] Add padding to Display Heading typography.
  packages/components/Atoms/Global/README.md
  packages/components/Atoms/Global/scss/settings/_font.scss
  packages/components/Atoms/Global/scss/settings/_variables.scss
  packages/components/Atoms/Global/scss/tools/_typography.scss
  packages/components/Atoms/Global/stories.js
Labels: ready for test

#493 [SDPA-2985] Fix acknowledgment field name and hero banner border.
  packages/components/Organisms/HeroBanner/HeroBanner.vue
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
Labels: ready to be merged

#495 [SDPA-3072] Hero banner fonts
  packages/components/Organisms/HeroBanner/HeroBanner.vue
  packages/ripple-nuxt-tide/modules/data-driven-component/components/TideMapPreventionFamilyViolence/TideMapPreventionFamilyViolence.vue
Labels: needs review

#477 [SDPSUP-608] Fix for grant accordion error if body is null.
  packages/ripple-nuxt-tide/modules/grant/pages/index.vue
Labels: ready for test

#497 [SDPA-3074] Added Winston modules in babel transpile
  packages/ripple-nuxt-tide/lib/module.js
Labels: needs review

#496 [SDPA-2723] Fix: A rpl-link 'target' prop change will update target attr
  packages/components/Atoms/Link/Link.vue
Labels: ready to be merged

#498 [SDPA-3091] Fixed search config
  Dockerfile.app
Labels: needs review

#486 [SDPA-372] Add Topic and Tags to end of Landing Page.
  packages/components/Atoms/MetaTag/index.vue
  packages/ripple-nuxt-tide/modules/landing-page/pages/index.vue
Labels: ready to be merged

#489 [SDPA-2988] Adds topic and tags search results page
  examples/vic-gov-au/test/e2e/integration/core-modules/search/topic-tags-search.feature
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  packages/ripple-nuxt-tide/modules/search/lib/search/module.js
  packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
  packages/ripple-nuxt-tide/modules/search/module.js
  packages/ripple-nuxt-tide/modules/search/pages/TopicTagSearch.vue
  packages/ripple-test-tools/step_definitions/common/components.js
Labels: ready to be merged

#492 [SDPA-369] Page topic tags
  packages/ripple-nuxt-tide/lib/components/AppTopicTags.vue
  packages/ripple-nuxt-tide/modules/landing-page/pages/index.vue
  packages/ripple-nuxt-tide/modules/page/pages/index.vue
Labels: ready to be merged

#487 [SDPA-2976] Fetch alert notifications from site taxonomy
  examples/vic-gov-au/package.json
  examples/vic-gov-au/test/e2e/fixtures/alert/1-BE-Alert-1.yml
  examples/vic-gov-au/test/e2e/fixtures/alert/1-BE-Alert-2.yml
  examples/vic-gov-au/test/e2e/fixtures/alert/1-BE-Alert-3.yml
  examples/vic-gov-au/test/e2e/integration/core-modules/alert/alert.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/authenticatedContent/authenticated-content/step_definition.js
  packages/components/Molecules/Alert/Alert.vue
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  packages/ripple-nuxt-tide/lib/templates/plugin.js
  packages/ripple-nuxt-tide/modules/alert/components/TideAlert.vue
  packages/ripple-nuxt-tide/modules/alert/localstorage.js
  packages/ripple-nuxt-tide/modules/alert/module.js
  packages/ripple-nuxt-tide/modules/alert/plugin.js
  packages/ripple-nuxt-tide/modules/site/plugin.js
  packages/ripple-test-tools/step_definitions/common/global.js
  packages/ripple-test-tools/step_definitions/common/utils.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#500 [SDPA-3045] Added request id in all route requests
  examples/vic-gov-au/store/index.js
  packages/ripple-nuxt-tide/lib/core/logger.js
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/core/tide-helper.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/lib/server-middleware/request-id.js
  packages/ripple-nuxt-tide/lib/server-middleware/request-log.js
  packages/ripple-nuxt-tide/lib/templates/plugin.js
  packages/ripple-nuxt-tide/lib/templates/request-id.js
  packages/ripple-nuxt-tide/modules/publication/tide.middleware.js
  packages/ripple-nuxt-tide/modules/site/plugin.js
  packages/ripple-nuxt-tide/package.json
  yarn.lock
Labels: ready to be merged

#501 [SDPA-1888] Fix: Safari hero banner graphic glitch.
  packages/components/Molecules/Layout/PageLayout.vue
Labels: ready to be merged

#467 [SDPA-1986] nuxt events feed
  examples/vic-gov-au/nuxt.config.js
  examples/vic-gov-au/tide/modules/event/formdata.js
  examples/vic-gov-au/tide/modules/event/helpers.js
  examples/vic-gov-au/tide/modules/event/mapping-fetchers.js
  examples/vic-gov-au/tide/modules/event/mapping-filters.js
  examples/vic-gov-au/tide/modules/event/module.js
  examples/vic-gov-au/tide/modules/event/pages/index.vue
  examples/vic-gov-au/tide/modules/event/pages/search.vue
  examples/vic-gov-au/tide/modules/event/tide.config.js
  examples/vic-gov-au/tide/modules/event/tide.load-components.js
  examples/vic-gov-au/tide/modules/event/tide.page-types.js
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/core/tracking.js
  packages/ripple-nuxt-tide/modules/event/pages/index.vue
  packages/ripple-nuxt-tide/test/unit/tracking.test.js
Labels: ready to be merged

#506 Release v1.1.0
  examples/vic-gov-au/package.json
  lerna.json
  packages/components/Atoms/Button/package.json
  packages/components/Atoms/Global/package.json
  packages/components/Atoms/Grid/package.json
  packages/components/Atoms/Icon/package.json
  packages/components/Atoms/Link/package.json
  packages/components/Atoms/MetaTag/package.json
  packages/components/Molecules/Alert/package.json
  packages/components/Molecules/AnchorLinks/package.json
  packages/components/Molecules/Breadcrumbs/package.json
  packages/components/Molecules/Card/package.json
  packages/components/Molecules/Contact/package.json
  packages/components/Molecules/DescriptionList/package.json
  packages/components/Molecules/DocumentLink/package.json
  packages/components/Molecules/EmbeddedVideo/package.json
  packages/components/Molecules/Figure/package.json
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Layout/package.json
  packages/components/Molecules/List/package.json
  packages/components/Molecules/Map/package.json
  packages/components/Molecules/Pagination/package.json
  packages/components/Molecules/PublishDateAndAuthor/package.json
  packages/components/Molecules/RelatedLinks/package.json
  packages/components/Molecules/Search/package.json
  packages/components/Molecules/ShareThis/package.json
  packages/components/Molecules/Sitemap/package.json
  packages/components/Molecules/Timeline/package.json
  packages/components/Molecules/WhatsNext/package.json
  packages/components/Organisms/Accordion/package.json
  packages/components/Organisms/CallToAction/package.json
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignSecondary/package.json
  packages/components/Organisms/Event/package.json
  packages/components/Organisms/Grants/package.json
  packages/components/Organisms/HeroBanner/package.json
  packages/components/Organisms/ImageGallery/package.json
  packages/components/Organisms/Markup/package.json
  packages/components/Organisms/News/package.json
  packages/components/Organisms/Profile/package.json
  packages/components/Organisms/Publication/package.json
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteHeader/package.json
  packages/components/Organisms/SiteSectionNavigation/package.json
  packages/components/Organisms/UpdatedDate/package.json
  packages/create-ripple-app/package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  src/package.json
Labels: ready to be merged

#509 [SDPA-3034] Card Profile
  packages/components/Molecules/Card/CardHonourRoll.vue
  packages/components/Molecules/Card/CardProfile.vue
  packages/components/Molecules/Card/README.md
  packages/components/Molecules/Card/index.js
  packages/components/Molecules/Card/stories.js
  packages/components/Molecules/Search/SearchResults.vue
  packages/ripple-nuxt-tide/modules/profile/pages/search.vue
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#503 [SDPA-2965] Accordion print styling.
  packages/components/Atoms/MetaTag/index.vue
  packages/components/Organisms/Accordion/Accordion.vue
Labels: ready to be merged
