Repository dpc-sdp/ripple, pull requests merged in 2019-05, with the labels that each got.

#341 [SDPA-2467] Fix hover on social links.
  packages/Molecules/ShareThis/index.vue
Labels: ready for test

#340 [SDPA-2466] Fix for selected item not being displayed for single select.
  packages/Molecules/Form/Checkbox.vue
  packages/Molecules/Form/__tests__/fieldRplSelect.test.js
  packages/Molecules/Form/fields/fieldRplselect.vue
  src/storybook-components/PageForm.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#343 Use span instead of div for innerwrap
  packages/Atoms/Link/Link.vue
  packages/Molecules/Card/CardEmergencyContact.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: URGENT, ready for test

#342 Release/v1.0.0 alpha.73
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#345 Release/v1.0.0 alpha.74
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#346 [SDPSUP-336] : Re-add JIRA integration
  .lagoon.yml
Labels: needs review

#348 [SDPA-2481] JIRA Integration test
  .lagoon.yml
Labels: needs review

#335 [SDPA-1606] Adding Accordion to Ripple.
  package-lock.json
  package.json
  packages/Atoms/Global/mixins/uniqueid.js
  packages/Organisms/Accordion/.npmignore
  packages/Organisms/Accordion/Accordion.vue
  packages/Organisms/Accordion/LICENSE
  packages/Organisms/Accordion/README.md
  packages/Organisms/Accordion/index.js
  packages/Organisms/Accordion/package.json
  packages/Organisms/Accordion/stories.js
  packages/Organisms/Markup/README.md
  src/storybook-components/PageAccordion.vue
  src/storybook-components/_data/demoData.js
  src/storybook-components/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review, ready for test

#350 [SDPA-2310] Updated map from latest code
  .storybook/webpack.config.js
  package-lock.json
  package.json
  packages/Molecules/Map/ButtonClose/index.vue
  packages/Molecules/Map/CloseButton.vue
  packages/Molecules/Map/Map.vue
  packages/Molecules/Map/MapIndicator.vue
  packages/Molecules/Map/MapIndicator/index.vue
  packages/Molecules/Map/README.md
  packages/Molecules/Map/lib/ol.js
  packages/Molecules/Map/package.json
  packages/Molecules/Map/stories.js
  src/storybook-components/MapVicFreeWifi.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#353 Release/v1.0.0 alpha.75
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#358 [SDPSUP-358] : Add rpl-hidden class
  packages/Atoms/Global/scss/utilities/_visibility.scss
Labels: ready to be merged

#360 #359 PageLayout columns
  packages/Molecules/Layout/PageLayout.vue
  packages/Molecules/Layout/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#352 [SDPA-2519] Add specific print url to links.
  packages/Atoms/Global/index.js
  packages/Atoms/Link/Link.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#354 [SDPA-2379] Publication download and print block.
  package-lock.json
  packages/Atoms/Icon/assets/img/rpl_icon_print.svg
  packages/Molecules/DocumentLink/DocumentLink.vue
  packages/Molecules/DocumentLink/scss/_document-link.scss
  packages/Organisms/Publication/PublicationDownloadPrint.vue
  packages/Organisms/Publication/index.js
  packages/Organisms/Publication/package.json
  packages/Organisms/Publication/stories.js
  src/storybook-components/PagePublication.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#262 Feature/package dependencies
  CONTRIBUTING.md
  package-lock.json
  packages/Atoms/Grid/README.md
  packages/Atoms/Grid/package.json
  packages/Molecules/AnchorLinks/index.vue
  packages/Molecules/Contact/README.md
  packages/Molecules/Contact/index.vue
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/README.md
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/README.md
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Form/README.md
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/README.md
  packages/Molecules/Layout/package.json
  packages/Molecules/List/README.md
  packages/Molecules/List/package.json
  packages/Molecules/Map/README.md
  packages/Molecules/Map/package.json
  packages/Molecules/RelatedLinks/index.vue
  packages/Molecules/Search/README.md
  packages/Molecules/Search/package.json
  packages/Molecules/WhatsNext/index.vue
  packages/Organisms/CallToAction/README.md
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/README.md
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/README.md
  packages/Organisms/CampaignSecondary/index.vue
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Grants/README.md
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/README.md
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/README.md
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/Markup.vue
  packages/Organisms/Markup/README.md
  packages/Organisms/Markup/package.json
  packages/Organisms/News/NewsListing.vue
  packages/Organisms/Publication/README.md
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteHeader/README.md
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/README.md
  packages/Organisms/SiteSectionNavigation/package.json
  scripts/generate-dependencies/dependency-utils.js
  scripts/generate-dependencies/generate-dependencies.js
Labels: needs review

#324 [SDPA-1578] Add focus outline to header / footer.
  packages/Atoms/Global/scss/_tools.scss
  packages/Atoms/Global/scss/settings/_variables.scss
  packages/Atoms/Global/scss/tools/_focus.scss
  packages/Atoms/MetaTag/index.vue
  packages/Molecules/Search/SearchForm.vue
  packages/Organisms/SiteFooter/index.vue
  packages/Organisms/SiteHeader/index.vue
  packages/Organisms/SiteHeader/menu.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#328 [SDPA-1097] Define line heights for each font-size with a background.
  packages/Atoms/Global/scss/settings/_font.scss
  packages/Atoms/Global/scss/tools/_typography.scss
  packages/Atoms/Global/stories.js
  src/storybook-components/Fonts.vue
  src/storybook-components/Typography.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#365 Release/1.0.0 alpha.76
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#367 [SDPSUP-344] Added routes and monitoring URLs to .lagoon.yml.
  .lagoon.yml
Labels: needs review

#364 [SDPA-2417] Add PublicationImage.
  package-lock.json
  packages/Atoms/Icon/assets/img/rpl_icon_download.svg
  packages/Atoms/Icon/assets/img/rpl_icon_table.svg
  packages/Molecules/Figure/index.vue
  packages/Organisms/ImageGallery/FullscreenImage.vue
  packages/Organisms/ImageGallery/ImageGallery.vue
  packages/Organisms/ImageGallery/README.md
  packages/Organisms/ImageGallery/index.js
  packages/Organisms/ImageGallery/scss/_image_gallery.scss
  packages/Organisms/Publication/PublicationImage.vue
  packages/Organisms/Publication/README.md
  packages/Organisms/Publication/index.js
  packages/Organisms/Publication/package.json
  packages/Organisms/Publication/stories.js
  src/storybook-components/PagePublication.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#368 [SDPSUP-336] Added JIRA credential environment variables and dynamic …
  .lagoon.yml
  scripts/jira-post-comment.sh
Labels: ready to be merged

#351 [SDPA-2485] Add xlink:href back to fix ios safari issue
  packages/Organisms/CampaignPrimary/index.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#362 [SDPA-1597] Adds styled radio buttons.
  packages/Molecules/Form/Checkbox.vue
  packages/Molecules/Form/index.vue
  packages/Molecules/Form/scss/_form.scss
Labels: ready to be merged

#300 [SDPA-1576] Change placeholder colour to meet WCAG contrast.
  packages/Molecules/Form/index.vue
  packages/Molecules/Form/scss/_form.scss
Labels: ready to be merged

#363 [SDPA-1598] Adjusts Pagination spacing to meet hit target size.
  packages/Molecules/Pagination/index.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#370 [SDPA-2569] Fix colour for links in RplMarkup.
  packages/Atoms/Icon/TextIcon.vue
  packages/Atoms/Link/TextLink.vue
  packages/Molecules/Alert/AlertBase.vue
  packages/Organisms/HeroBanner/HeroBanner.vue
  packages/Organisms/HeroBanner/HeroBannerCta.vue
  packages/Organisms/HeroBanner/IntroBanner.vue
  packages/Organisms/Markup/Markup.vue
  packages/Organisms/Markup/stories.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#294 [SDPA-2224] Adds aria-label to datepicker.
  packages/Molecules/Form/fields/fieldRpldatepicker.vue
  packages/Molecules/Form/formPikaday.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#371 Release/v1.0.0 alpha.77
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DescriptionList/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#372 Check for window before calling window.print for SSR
  packages/Organisms/Publication/PublicationDownloadPrint.vue
Labels: ready for test

#366 Added custom icon support for adding new and overriding existing icons.
  .storybook/config.js
  .storybook/webpack.config.js
  packages/Atoms/Icon/Icon.vue
  packages/Atoms/Icon/icon-library.js
  packages/Atoms/Icon/index.js
  packages/Atoms/Icon/stories.js
  src/storybook-components/scss/story.scss
  static/custom_icons/rpl_icon_custom_icon.svg
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#374 Release/1.0.0 alpha.79
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DescriptionList/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
  test/__snapshots__/storyshots.test.js.snap
Labels: needs review

#376 Feature/1.0.0 alpha.80
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DescriptionList/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Map/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/Accordion/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/Profile/package.json
  packages/Organisms/Publication/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#378 Highlightjs version bump. Fixes firefox / safari error.
  package-lock.json
Labels: needs review

#379 [SDPA-2618] Only show border on print if list items exist before.
  packages/Organisms/Publication/PublicationDownloadPrint.vue
Labels: needs review
