Repository dpc-sdp/ripple, pull requests merged in 2019-01, with the labels that each got.

#176 [SDPA-1569] Adds required field indicator on form fields.
  packages/Molecules/Form/index.vue
  packages/Molecules/Form/scss/_form.scss
Labels: ready to be merged

#187 Feature/1.0.0 alpha.40
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#181 [SDPA-1623] Changed phone number in rpl-contact to object to add title.
  packages/Molecules/Contact/index.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#183 [SDPA-1477] Adds video variant to rpl-campaign-secondary.
  packages/Molecules/EmbeddedVideo/index.vue
  packages/Organisms/CampaignSecondary/index.vue
  packages/Organisms/CampaignSecondary/stories.js
  src/storybook-components/Page.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged, resolve conflict

#190 Feature/1.0.0 alpha.41
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#188 [SDPA-1205] Reset pagination arrow on totalStep change.
  packages/Molecules/Pagination/index.vue
  packages/Molecules/Search/stories.js
  src/storybook-components/SearchPage.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#184 [SDPA-691] Fixed specificity issue with campaign primary cta margin.
  packages/Organisms/CampaignPrimary/index.vue
Labels: ready to be merged

#182 [SDPA-1633] set search field focus on mount.
  packages/Molecules/Search/SearchForm.vue
  packages/Organisms/SiteHeader/search.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#191 [SDPAPC-3] Added logout button to site header.
  packages/Atoms/Global/scss/settings/_color.scss
  packages/Organisms/SiteHeader/index.vue
  packages/Organisms/SiteHeader/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#193 Release/v1.0.0 alpha.42
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#179 [SDPA-1588] Adds aria-label to campaign primary image link
  packages/Organisms/CampaignPrimary/index.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#186 [SDPA-1614] Fix ie issue with card carousel. Add story to template.
  packages/Molecules/Card/no-ssr/CardCarousel.vue
  src/storybook-components/Page.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#196 [SDPSUP-49] Fixed CampaignPrimary arrow not acting as hyperlink
  packages/Organisms/CampaignPrimary/index.vue
Labels: needs review

#195 [SDPA-1622] VFG RplMarkup field added.
  packages/Molecules/Form/fields/fieldRplmarkup.vue
  packages/Molecules/Form/index.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#194 [SDPA-559] Adds focus trap to open site header menu.
  package-lock.json
  packages/Molecules/Search/package.json
  packages/Organisms/SiteHeader/index.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#197 Release/v1.0.0 alpha.43
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#201 [SDPA-1727] Form fixes.
  packages/Molecules/Form/Checkbox.vue
  packages/Molecules/Form/fields/fieldRpldatepicker.vue
  packages/Molecules/Form/formPikaday.vue
  src/storybook-components/PageForm.vue
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#204 Feature/1.0.0 alpha.44
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#199 [SDPSUP-39] Fixed unresponsive breakpoint on CampaignPrimary banner.
  packages/Organisms/CampaignPrimary/index.vue
Labels: needs review

#200 [SDPA-1729] Adds wrapper for vueMultiselect to use with object arrays.
  package-lock.json
  packages/Molecules/Form/fields/fieldRplchecklist.vue
  packages/Molecules/Form/fields/fieldRplselect.vue
  packages/Molecules/Form/index.vue
  packages/Molecules/Form/package.json
  packages/Molecules/Form/stories.js
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#205 v1.0.0-alpha.45
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#207 Removes scrollto on submit
  package-lock.json
  packages/Molecules/Form/fields/fieldRplmarkup.vue
  packages/Molecules/Form/index.vue
  packages/Molecules/Form/package.json
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#206 Added a script `npm run package-dependencies`
  CONTRIBUTING.md
  package.json
  scripts/generate-dependencies/generate-dependencies.js
Labels: ready to be merged

#208 Release/v1.0.0 alpha.46
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#209 [SDPA-1691] Calls validate form on submit and before submission
  package-lock.json
  packages/Molecules/Form/index.vue
  packages/Molecules/Form/package.json
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#211 [SDPA-1678] Fixed the regex issue
  package-lock.json
  packages/Atoms/Icon/README.md
  packages/Atoms/Icon/TextIcon.vue
  packages/Atoms/Icon/stories.js
  packages/Molecules/Form/README.md
  packages/Molecules/Form/index.vue
  packages/Molecules/Form/package.json
  packages/Molecules/Search/package.json
  packages/Organisms/Markup/README.md
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#213 Release/v1.0.0 alpha.48
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: ready to be merged

#202 [SDPSUP-8] Fixed vic logo appearing on small screens
  package-lock.json
  packages/Atoms/Global/assets/images/logo-primary.png
  packages/Atoms/Global/index.js
  packages/Organisms/SiteHeader/index.vue
  src/storybook-components/_data/demoData.js
  static/cobrand-logo.png
  static/logo.svg
  test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#216 [SDPA-1787] removes vue-click-outside directive
  package-lock.json
  packages/Molecules/Form/fields/fieldRplchecklist.vue
  packages/Molecules/Form/package.json
Labels: ready to be merged

#214 v1.0.0-alpha.49
  lerna.json
  package-lock.json
  package.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#217 Release/v1.0.0 alpha.50
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#219 [SDPA-1780] Removed undesigned color name
  packages/Atoms/Global/scss/settings/_color.scss
  packages/Organisms/SiteHeader/index.vue
Labels: ready for test

#220 Release/1.0.0 alpha.51
  lerna.json
  package-lock.json
  packages/Atoms/Button/package.json
  packages/Atoms/Global/package.json
  packages/Atoms/Grid/package.json
  packages/Atoms/Icon/package.json
  packages/Atoms/Link/package.json
  packages/Atoms/MetaTag/package.json
  packages/Molecules/Alert/package.json
  packages/Molecules/AnchorLinks/package.json
  packages/Molecules/Breadcrumbs/package.json
  packages/Molecules/Card/package.json
  packages/Molecules/Contact/package.json
  packages/Molecules/DocumentLink/package.json
  packages/Molecules/EmbeddedVideo/package.json
  packages/Molecules/Figure/package.json
  packages/Molecules/Form/package.json
  packages/Molecules/Layout/package.json
  packages/Molecules/List/package.json
  packages/Molecules/Pagination/package.json
  packages/Molecules/PublishDateAndAuthor/package.json
  packages/Molecules/RelatedLinks/package.json
  packages/Molecules/Search/package.json
  packages/Molecules/ShareThis/package.json
  packages/Molecules/Sitemap/package.json
  packages/Molecules/Timeline/package.json
  packages/Molecules/WhatsNext/package.json
  packages/Organisms/CallToAction/package.json
  packages/Organisms/CampaignPrimary/package.json
  packages/Organisms/CampaignSecondary/package.json
  packages/Organisms/Event/package.json
  packages/Organisms/Grants/package.json
  packages/Organisms/HeroBanner/package.json
  packages/Organisms/ImageGallery/package.json
  packages/Organisms/Markup/package.json
  packages/Organisms/News/package.json
  packages/Organisms/SiteFooter/package.json
  packages/Organisms/SiteHeader/package.json
  packages/Organisms/SiteSectionNavigation/package.json
  packages/Organisms/UpdatedDate/package.json
Labels: needs review

#221 Add a test to check versions of packages against the lerna version.
  test/package-version.test.js
Labels: ready to be merged

#218 [SDPA-1789] Adds vue-on-click-outside to close rplchecklist on click outside
  package-lock.json
  packages/Molecules/Form/fields/fieldRplchecklist.vue
  packages/Molecules/Form/package.json
Labels: ready for test

#225 Export markupTranspiler for use in unit tests
  packages/Organisms/Markup/Markup.vue
  packages/Organisms/Markup/index.js
  packages/Organisms/Markup/package.json
  packages/Organisms/Markup/stories.js
Labels: needs review

#224 [SDPA-1769] Clear search form button
  packages/Molecules/Form/Checkbox.vue
  packages/Molecules/Form/fields/fieldRplclearform.vue
  packages/Molecules/Form/fields/fieldRpldatepicker.vue
  packages/Molecules/Form/fields/fieldRplselect.vue
  packages/Molecules/Form/formPikaday.vue
  packages/Molecules/Form/index.vue
  src/storybook-components/_data/demoData.js
  test/__snapshots__/storyshots.test.js.snap
Labels: ready for test
