Repository dpc-sdp/ripple, pull requests merged in 2019-10, with the labels that each got.

#545 [SDPA-3184] Setup timeout for Tide request
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/core/tide-helper.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/lib/templates/axios.js
  packages/ripple-nuxt-tide/lib/templates/plugin.js
  packages/ripple-nuxt-tide/modules/event/mapping-filters.js
  packages/ripple-nuxt-tide/modules/news/mapping-filters.js
  packages/ripple-nuxt-tide/modules/publication/tide.middleware.js
  packages/ripple-nuxt-tide/test/unit/tide.test.js
Labels: ready to be merged

#535 [SDPSUP-669] Added example for using Ripple in Vue.js(Not Nuxt)
  .circleci/config.yml
  README.md
  examples/vue-example-app/.gitignore
  examples/vue-example-app/README.md
  examples/vue-example-app/babel.config.js
  examples/vue-example-app/cypress.json
  examples/vue-example-app/package-lock.json
  examples/vue-example-app/package.json
  examples/vue-example-app/src/App.vue
  examples/vue-example-app/src/assets/logo.png
  examples/vue-example-app/src/components/HelloRipple.vue
  examples/vue-example-app/src/main.js
  examples/vue-example-app/src/variables.scss
  examples/vue-example-app/test/e2e/integration/common/index.js
  examples/vue-example-app/test/e2e/integration/smoke/ripple.feature
  examples/vue-example-app/test/e2e/integration/smoke/ripple/step_definition.js
  examples/vue-example-app/test/e2e/plugins/index.js
  examples/vue-example-app/test/e2e/support/commands.js
  examples/vue-example-app/test/e2e/support/index.js
  examples/vue-example-app/vue.config.js
  packages/components/Atoms/Global/README.md
  yarn.lock
Labels: ready to be merged

#548 [SDPA-2900] Landing page e2e test
  examples/vic-gov-au/test/e2e/fixtures/landingPage/5-be-land-3-landing-page-complete-test.html
  examples/vic-gov-au/test/e2e/fixtures/landingPage/5-be-land-3-landing-page-complete-test.yml
  examples/vic-gov-au/test/e2e/integration/core-modules/landingPage/LandingPage.feature
  packages/components/Molecules/Card/no-ssr/CardCarousel.vue
  packages/components/Organisms/Event/LatestEvents.vue
  packages/ripple-test-tools/step_definitions/common/components.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready for test

#554 Added different timeout for CI test
  .circleci/config.yml
  packages/ripple-nuxt-tide/lib/core/tide.js
Labels: ready to be merged

#556 Fix issues with e2e-vic-gov-au tests
  .circleci/config.yml
  examples/vic-gov-au/test/e2e/fixtures/authenticatedContent/taxonomy.yml
  examples/vic-gov-au/test/e2e/fixtures/landingPage/1-FE-auth-content-4.yml
  examples/vic-gov-au/test/e2e/fixtures/landingPage/5-be-land-3-landing-page-complete-test.html
  examples/vic-gov-au/test/e2e/fixtures/page/8-BE-page-1-basic-page.yml
  examples/vic-gov-au/test/e2e/fixtures/page/8-FE-page-1-figure.html
  examples/vic-gov-au/test/e2e/fixtures/snippets/BE-examplebody.html
  examples/vic-gov-au/test/e2e/fixtures/snippets/FE-examplebody.html
  examples/vic-gov-au/test/e2e/fixtures/snippets/blockquote.html
  examples/vic-gov-au/test/e2e/fixtures/snippets/callout.html
  examples/vic-gov-au/test/e2e/fixtures/snippets/document.html
  examples/vic-gov-au/test/e2e/integration/core-modules/alert/alert.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/authenticatedContent/authenticated-content.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/event/event.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/landingPage/AnchorLink.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/landingPage/AnchorLink/step_definition.js
  examples/vic-gov-au/test/e2e/integration/core-modules/landingPage/LandingPage.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/page/page.feature
  package.json
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/page/page.feature
  packages/ripple-test-tools/step_definitions/common/components.js
  packages/ripple-test-tools/tide-admin/index.js
  packages/ripple-test-tools/tide-admin/page-models.js
Labels: ready for test

#549 [SDPA-2470] Added bottom padding for cta component in xs screen.
  packages/components/Organisms/CampaignSecondary/index.vue
Labels: ready to be merged

#550 [SDPA-1967] Updated Honour role apply button text to match the design.
  packages/ripple-nuxt-tide/modules/profile/formdata.js
Labels: ready to be merged

#551 [SDPA-3192] Added Wordwrap mixin and used in rpl_banner_title.
  packages/components/Organisms/HeroBanner/HeroBanner.vue
Labels: ready to be merged

#553 [SDPA-3174] Added hero banner title size for smal & large screen.
  packages/components/Organisms/HeroBanner/HeroBanner.vue
Labels: ready to be merged

#552 [SDPA-3125] Added Flex for the small screen to make it two columns.
  packages/components/Molecules/RelatedLinks/index.vue
  packages/components/Molecules/WhatsNext/index.vue
Labels: ready to be merged

#559 [SDPA-3203] Added pagination correct number highlighting fix.
  packages/components/Molecules/Pagination/index.vue
  packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
Labels: ready for test

#528 [SDPA-2949] Fix: Search results query to support filter object.
  packages/ripple-nuxt-tide/modules/search/lib/search/module.js
  packages/ripple-nuxt-tide/test/unit/search.test.js
Labels: ready for test

#562 [SDPA-3338] decode issue
  packages/components/Organisms/Markup/markup-transpiler.js
  packages/ripple-nuxt-tide/test/unit/__fixtures__/markup-transpiler-html.js
  packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
  packages/ripple-nuxt-tide/test/unit/markup-transpiler.test.js
Labels: ready for test

#561 [SDPA-3270] Upgraded Nuxt to v2.9.2
  examples/basic-examples/package.json
  examples/vic-gov-au/package.json
  jest.config.js
  package.json
  packages/create-ripple-app/__tests__/__mocks__/v18/package.json
  packages/create-ripple-app/template/_package.json
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/modules/alert/components/TideAlert.vue
  packages/ripple-nuxt-tide/modules/landing-page/pages/index.vue
  packages/ripple-nuxt-tide/modules/publication/pages/index.vue
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  yarn.lock
Labels: ready for test

#557 [SDPA-3207] Added style change for CallToAction to match xs screen design.
  packages/components/Organisms/CallToAction/index.vue
Labels: ready for test

#572 [SDPA-3348] markup encode issue
  packages/components/Atoms/Global/utils/helpers.js
  packages/components/Atoms/Link/TextLink.vue
  packages/components/Molecules/DocumentLink/DocumentLink.vue
  packages/components/Organisms/Markup/markup-transpiler.js
  packages/ripple-nuxt-tide/lib/config/markup-plugins.js
  packages/ripple-nuxt-tide/lib/core/anchorlinks.js
  packages/ripple-nuxt-tide/lib/core/html-utilities.js
  packages/ripple-nuxt-tide/lib/core/mapping-filters.js
  packages/ripple-nuxt-tide/test/unit/__fixtures__/markup-transpiler-html.js
  packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
  packages/ripple-nuxt-tide/test/unit/anchorlinks.test.js
  packages/ripple-nuxt-tide/test/unit/html-utilities.test.js
  src/test/unit/helpers.test.js
Labels: ready for test

#566 [SDPL-96] Split fieldRplSelect into its own component
  packages/components/Molecules/Form/Select.vue
  packages/components/Molecules/Form/__tests__/RplSelect.test.js
  packages/components/Molecules/Form/fields/fieldRplselect.vue
  packages/components/Molecules/Form/index.js
  packages/components/Molecules/Form/stories.js
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#570 Update create ripple app
  examples/vic-gov-au/test/e2e/fixtures/grant/Forms/addgrant.json
  examples/vic-gov-au/test/e2e/fixtures/grant/Forms/tc9c.csv
  examples/vic-gov-au/test/e2e/fixtures/grant/Forms/tc9c_submission.json
  examples/vic-gov-au/test/e2e/fixtures/grant/Forms/tc9d.csv
  examples/vic-gov-au/test/e2e/integration/core-modules/alert/alert.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/authenticatedContent/authenticated-content.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/event/event.feature
  examples/vic-gov-au/test/e2e/integration/core-modules/page/page.feature
  examples/vic-gov-au/test/e2e/integration/core/content-preview/preview-content.feature
  examples/vic-gov-au/test/e2e/integration/smoke/Homepage.feature
  package.json
  packages/create-ripple-app/__tests__/new.test.js
  packages/create-ripple-app/cli.js
  packages/create-ripple-app/generators/new/saofile.js
  packages/create-ripple-app/template/_package.json
  packages/create-ripple-app/template/_tests/_common/test/e2e/README.md
  packages/create-ripple-app/template/_tests/_common/test/e2e/fixtures/snippets/BE-examplebody.html
  packages/create-ripple-app/template/_tests/_common/test/e2e/fixtures/snippets/FE-examplebody.html
  packages/create-ripple-app/template/_tests/_common/test/e2e/fixtures/snippets/blockquote.html
  packages/create-ripple-app/template/_tests/_common/test/e2e/fixtures/snippets/callout.html
  packages/create-ripple-app/template/_tests/_common/test/e2e/fixtures/snippets/document.html
  packages/create-ripple-app/template/_tests/_common/test/e2e/integration/core/content-preview/preview-content.feature
  packages/create-ripple-app/template/_tests/_common/test/e2e/integration/core/content-preview/preview-content/step_definition.js
  packages/create-ripple-app/template/_tests/_common/test/e2e/integration/core/global/quickexit.feature
  packages/create-ripple-app/template/_tests/_common/test/e2e/integration/custom/README.md
  packages/create-ripple-app/template/_tests/_common/test/e2e/integration/smoke/Homepage.feature
  packages/create-ripple-app/template/_tests/_common/test/e2e/integration/smoke/tide-is-up.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/alert/1-BE-Alert-1.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/alert/1-BE-Alert-2.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/alert/1-BE-Alert-3.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/event/2-BE-event-1.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/landingPage/1-FE-auth-content-4.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/landingPage/5-be-land-3-landing-page-complete-test.html
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/landingPage/5-be-land-3-landing-page-complete-test.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/page/8-BE-page-1-basic-page.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/profile/4-BE-Profile-1.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/fixtures/publication/17-BE-pub-1-Create-Parent-Page.yml
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/alert/alert.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/authenticatedContent/authenticated-content.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/authenticatedContent/authenticated-content/hooks.js
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/authenticatedContent/authenticated-content/step_definition.js
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/event/event.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/grant/grant.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/grant/submit-a-grant.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/landingPage/LandingPage.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/page/page.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core-modules/search/topic-tags-search.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core/content-preview/preview-content.feature
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core/content-preview/preview-content/step_definition.js
  packages/create-ripple-app/template/_tests/_modules/test/e2e/integration/core/global/quickexit.feature
  packages/create-ripple-app/template/nuxt/.sass-lint.yml
  packages/ripple-test-tools/package.json
  packages/ripple-test-tools/scripts/cucumberconvertor.js
  packages/ripple-test-tools/step_definitions/common/index.js
  packages/ripple-test-tools/step_definitions/common/modules/events.js
  packages/ripple-test-tools/tide-admin/index.js
  scripts/cucumberconvertor.js
Labels: ready for test

#567 [SDPA-3169] adds new branding
  README.md
  docs/SDP_Logo_VicGov_RGB.jpg
  docs/SDP_Ripple_product_logo_JPG.JPG
  docs/Salsa.png
Labels: ready to be merged

#579 Remove explicit file paths and fix bin command path
  packages/create-ripple-app/cli.js
  packages/create-ripple-app/generators/updates/18.0.0/saofile.js
  packages/create-ripple-app/package.json
  packages/create-ripple-app/template/_package.json
  packages/ripple-test-tools/package.json
  yarn.lock
Labels: needs review

#580 [SDPA-3389] embedded video error
  packages/components/Molecules/EmbeddedVideo/index.vue
  packages/components/Molecules/EmbeddedVideo/stories.js
  packages/components/Organisms/Markup/examplePlugins.js
  packages/ripple-nuxt-tide/lib/config/markup-plugins.js
  packages/ripple-nuxt-tide/test/unit/__fixtures__/markup-transpiler-html.js
  packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#581 Add dotenv file for new projects using create ripple app
  packages/create-ripple-app/generators/new/saofile.js
  packages/create-ripple-app/template/_.env
  packages/create-ripple-app/template/nuxt/.gitignore
Labels: ready to be merged

#584 [SDPA-3390] Alerts with no link FE crash fix.
  packages/ripple-nuxt-tide/modules/alert/plugin.js
Labels: ready for test

#585 Fixed create app update script typo
  packages/create-ripple-app/generators/updates/18.0.0/saofile.js
Labels: ready to be merged

#582 [SDPA-3310] Whatson event listing filtering by end date
  packages/ripple-nuxt-tide/modules/event/pages/search.vue
Labels: ready for test

#586 [SDPSUP-1056] Fixed gitignore in create app
  packages/create-ripple-app/generators/new/saofile.js
  packages/create-ripple-app/template/gitignore
Labels: ready to be merged
