Repository dpc-sdp/ripple, pull requests merged in 2020-02, with the labels that each got.

#627 [SDPA-3341] Publication print "contact us" component for parent.
  packages/ripple-nuxt-tide/modules/publication/pages/PrintAll.vue
Labels: ready for test

#630 [SDPA-3712] reduce js bundle size
  examples/basic-examples/nuxt.config.js
  examples/basic-examples/package.json
  examples/basic-examples/tide/modules/example-search/components/Search.vue
  examples/basic-examples/tide/modules/example-search/components/SearchSimple.vue
  examples/vic-gov-au/nuxt.config.js
  examples/vic-gov-au/package.json
  packages/components/Molecules/Form/fields/fieldRplchecklist.vue
  packages/components/Molecules/Form/formPikaday.vue
  packages/create-ripple-app/cli.js
  packages/create-ripple-app/generators/updates/18.0.0/saofile.js
  packages/create-ripple-app/generators/updates/20.0.0/saofile.js
  packages/create-ripple-app/generators/updates/install/saofile.js
  packages/create-ripple-app/package.json
  packages/create-ripple-app/template/_example/tide/modules/event/pages/search.vue
  packages/create-ripple-app/template/_package.json
  packages/create-ripple-app/template/nuxt/nuxt.config.js
  packages/ripple-nuxt-tide/lib/core/config-loader.js
  packages/ripple-nuxt-tide/lib/core/tide.js
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  packages/ripple-nuxt-tide/lib/templates/plugin.js
  packages/ripple-nuxt-tide/modules/alert/components/TideAlert.vue
  packages/ripple-nuxt-tide/modules/alert/plugin.js
  packages/ripple-nuxt-tide/modules/event/pages/search.vue
  packages/ripple-nuxt-tide/modules/grant/pages/search.vue
  packages/ripple-nuxt-tide/modules/profile/pages/search.vue
  packages/ripple-nuxt-tide/modules/publication/pages/PrintAll.vue
  packages/ripple-nuxt-tide/modules/search/index.js
  packages/ripple-nuxt-tide/modules/search/lib/search/getSearch.js
  packages/ripple-nuxt-tide/modules/search/lib/search/helpers.js
  packages/ripple-nuxt-tide/modules/search/lib/search/module.js
  packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
  packages/ripple-nuxt-tide/modules/search/module.js
  packages/ripple-nuxt-tide/modules/search/pages/TideSearch.vue
  packages/ripple-nuxt-tide/modules/search/templates/plugin-on-demand.js
  packages/ripple-nuxt-tide/modules/search/templates/plugin.js
  packages/ripple-nuxt-tide/modules/site/module.js
  packages/ripple-nuxt-tide/modules/site/templates/plugin.js
  packages/ripple-nuxt-tide/package.json
  yarn.lock
Labels: needs review

#629 [SDPA-3730] add class to events search form and webform
  packages/ripple-nuxt-tide/lib/core/tide-helper.js
  packages/ripple-nuxt-tide/modules/event/formdata.js
  packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
  packages/ripple-nuxt-tide/test/unit/tide.test.js
Labels: needs review

#597 CI fix
  .circleci/config.yml
Labels: DO NOT MERGE, DO NOT REVIEW

#633 [SDPSUP-1371] trim function for crad cta
  packages/components/Molecules/Card/CardCta.vue
  src/test/__snapshots__/storyshots.test.js.snap
Labels: ready to be merged

#636 Update improvement
  packages/create-ripple-app/README.md
  packages/create-ripple-app/cli.js
  packages/create-ripple-app/generators/updates/18.0.0/saofile.js
  packages/create-ripple-app/generators/updates/20.0.0/saofile.js
  packages/create-ripple-app/generators/updates/21.0.0/saofile.js
  packages/create-ripple-app/generators/updates/install/saofile.js
  packages/create-ripple-app/template/_package.json
  packages/create-ripple-app/template/_tests/_common/test/e2e/integration/smoke/tide-is-up.feature
  packages/create-ripple-app/template/nuxt/nuxt.config.js
Labels: ready for test
