Repository dpc-sdp/ripple, pull requests merged in 2020-01, with the labels that each got.

#619 Add ripple-list-group dependency in nuxt-tide
  packages/components/Molecules/ListGroup/index.js
  packages/ripple-nuxt-tide/package.json
Labels: ready for test

#623 [SDPA-3652] publication author doesn't show
  examples/vic-gov-au/test/e2e/integration/core-modules/publication/publication.feature
  packages/components/Organisms/Publication/PublicationAuthorInformation.vue
  packages/components/Organisms/Publication/package.json
  yarn.lock
Labels: needs review

#622 [SDPA-3421] Fix embedded video issues with no transcript and add tests
  examples/vic-gov-au/test/e2e/fixtures/media/embedded-video-no-transcript.yml
  examples/vic-gov-au/test/e2e/fixtures/media/embedded-video.yml
  examples/vic-gov-au/test/e2e/integration/core-modules/media/media.feature
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/modules/media/components/EmbeddedVideo.vue
  packages/ripple-test-tools/commands.js
  packages/ripple-test-tools/step_definitions/common/components.js
  packages/ripple-test-tools/step_definitions/common/modules/media.js
  packages/ripple-test-tools/step_definitions/common/navigation.js
  packages/ripple-test-tools/tide-admin/index.js
Labels: ready to be merged

#624 Release 1.5.7
  examples/basic-examples/package.json
  examples/vic-gov-au/package.json
  examples/vue-example-app/package-lock.json
  examples/vue-example-app/package.json
  lerna.json
  packages/components/Atoms/Button/package.json
  packages/components/Atoms/Global/package.json
  packages/components/Atoms/Grid/package.json
  packages/components/Atoms/Icon/package.json
  packages/components/Atoms/Link/package.json
  packages/components/Atoms/MetaTag/package.json
  packages/components/Molecules/Alert/package.json
  packages/components/Molecules/AnchorLinks/package.json
  packages/components/Molecules/Breadcrumbs/package.json
  packages/components/Molecules/Card/package.json
  packages/components/Molecules/Contact/package.json
  packages/components/Molecules/DescriptionList/package.json
  packages/components/Molecules/DocumentLink/package.json
  packages/components/Molecules/EmbeddedVideo/package.json
  packages/components/Molecules/Figure/package.json
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Layout/package.json
  packages/components/Molecules/List/package.json
  packages/components/Molecules/ListGroup/package.json
  packages/components/Molecules/Map/package.json
  packages/components/Molecules/Pagination/package.json
  packages/components/Molecules/PublishDateAndAuthor/package.json
  packages/components/Molecules/RelatedLinks/package.json
  packages/components/Molecules/Search/package.json
  packages/components/Molecules/ShareThis/package.json
  packages/components/Molecules/Sitemap/package.json
  packages/components/Molecules/Timeline/package.json
  packages/components/Molecules/WhatsNext/package.json
  packages/components/Organisms/Accordion/package.json
  packages/components/Organisms/CallToAction/package.json
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignSecondary/package.json
  packages/components/Organisms/Event/package.json
  packages/components/Organisms/Grants/package.json
  packages/components/Organisms/HeroBanner/package.json
  packages/components/Organisms/ImageGallery/package.json
  packages/components/Organisms/Markup/package.json
  packages/components/Organisms/News/package.json
  packages/components/Organisms/Profile/package.json
  packages/components/Organisms/Publication/package.json
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteHeader/package.json
  packages/components/Organisms/SiteSectionNavigation/package.json
  packages/components/Organisms/UpdatedDate/package.json
  packages/create-ripple-app/package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  src/package.json
  yarn.lock
Labels: needs review

#620 Fix failing alert test
  examples/vic-gov-au/test/e2e/integration/core-modules/publication/publication.feature
  packages/ripple-test-tools/step_definitions/common/global.js
Labels: ready to be merged

#618 Feature/vicpol patch changes
  packages/components/Atoms/Link/TextLink.vue
  packages/ripple-nuxt-tide/lib/components/AppForm.vue
Labels: ready to be merged

#621 [SDPA-3619] custom font support
  examples/basic-examples/assets/_theme.scss
  examples/basic-examples/nuxt.config.js
  examples/basic-examples/test/e2e/integration/custom/fonts.feature
  examples/basic-examples/test/e2e/integration/custom/fonts/step_definition.js
  packages/components/Atoms/Global/README.md
  packages/components/Atoms/Global/assets/fonts/VIC-Bold.eot
  packages/components/Atoms/Global/assets/fonts/VIC-Bold.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-BoldItalic.eot
  packages/components/Atoms/Global/assets/fonts/VIC-BoldItalic.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-ExtraLight.eot
  packages/components/Atoms/Global/assets/fonts/VIC-ExtraLight.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-ExtraLightItalic.eot
  packages/components/Atoms/Global/assets/fonts/VIC-ExtraLightItalic.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-Italic.eot
  packages/components/Atoms/Global/assets/fonts/VIC-Italic.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-Light.eot
  packages/components/Atoms/Global/assets/fonts/VIC-Light.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-LightItalic.eot
  packages/components/Atoms/Global/assets/fonts/VIC-LightItalic.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-Medium.eot
  packages/components/Atoms/Global/assets/fonts/VIC-Medium.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-MediumItalic.eot
  packages/components/Atoms/Global/assets/fonts/VIC-MediumItalic.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-Regular.eot
  packages/components/Atoms/Global/assets/fonts/VIC-Regular.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-SemiBold.eot
  packages/components/Atoms/Global/assets/fonts/VIC-SemiBold.ttf
  packages/components/Atoms/Global/assets/fonts/VIC-SemiBoldItalic.eot
  packages/components/Atoms/Global/assets/fonts/VIC-SemiBoldItalic.ttf
  packages/components/Atoms/Global/scss/elements/_font.scss
  packages/components/Molecules/Card/CardEvent.vue
  packages/components/Molecules/Card/CardPromotion.vue
  packages/components/Molecules/Card/mixins/cardtrimfield.js
  packages/ripple-nuxt-ui/lib/templates/plugin.js
Labels: ready for test
