Repository dpc-sdp/ripple, pull requests merged in 2020-09, with the labels that each got.

#748 [SDPSUP-1925] : Add support for multiple field sorts
  packages/ripple-nuxt-tide/modules/search/lib/search/services/elasticsearch/lib/api.js
Labels: needs review

#765 [SDPA-4301] fix storybook knobs not working in storybook
  packages/components/Atoms/Button/__snapshots__/stories.storyshot
  packages/components/Atoms/Button/__tests__/button.test.js
  packages/components/Atoms/Button/index.vue
  packages/components/Atoms/Button/stories.js
  packages/components/Molecules/Card/stories.js
  packages/components/Molecules/Form/stories.js
  packages/components/Molecules/Layout/stories.js
Labels: ready for test

#769 Feature/sdpa 4574 timeline summary field changes
  packages/components/Molecules/Timeline/Timeline.vue
  packages/components/Molecules/Timeline/__snapshots__/stories.storyshot
  packages/ripple-nuxt-tide/modules/landing-page/mapping-filters.js
Labels: needs review

#772 [SDPSUP-2024] Add html lang attr from meta tag
  packages/ripple-nuxt-tide/lib/core/tide-helper.js
  packages/ripple-nuxt-tide/lib/middleware/page-head.js
Labels: needs review

#768 [SDPA-3630] Remove capitalisation from quotation author
  packages/components/Organisms/Markup/Markup.vue
Labels: ready to be merged

#779 [SDPA-4608] : Add imageless support for CTA component
  packages/components/Organisms/CallToAction/index.vue
Labels: ready for test

#778 [SDPA-4584] display h3 headings in table of content
  packages/components/Molecules/AnchorLinks/__snapshots__/stories.storyshot
  packages/components/Molecules/AnchorLinks/assets/.DS_Store
  packages/components/Molecules/AnchorLinks/assets/images/list-indent.svg
  packages/components/Molecules/AnchorLinks/index.vue
  packages/components/Molecules/AnchorLinks/stories.js
  packages/ripple-nuxt-tide/lib/config/markup-plugins.js
  packages/ripple-nuxt-tide/lib/core/anchorlinks.js
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  packages/ripple-nuxt-tide/test/unit/anchorlinks.test.js
Labels: ready for test, ready to be merged

#764 [SDPA-4326] fix text icon component issue
  packages/components/Atoms/Icon/Icon.vue
  packages/components/Atoms/Icon/TextIcon.vue
  packages/components/Atoms/Icon/__tests__/text-icon.test.js
  packages/components/Atoms/Icon/icon-library.stories.mdx
  packages/components/Atoms/Icon/icon.stories.mdx
  packages/components/Atoms/Icon/stories.js
  packages/components/Atoms/Icon/textIcon.stories.mdx
  packages/components/Molecules/Form/__snapshots__/stories.storyshot
  packages/components/Organisms/ImageGallery/__snapshots__/stories.storyshot
Labels: ready for test, ready to be merged

#777 [SDPA-4566] Added styling changes.
  packages/components/Organisms/HeroBanner/HeroBanner.vue
  packages/components/Organisms/HeroBanner/IntroBanner.vue
Labels: needs review

#771 [DDIDO-186] Added non-prod and Fixed Prod Routes
  .lagoon.yml
Labels: needs review

#785 Feature/sdpa 4568 add markup callout wrapper
  packages/components/Atoms/Global/scss/settings/_colorcore.scss
  packages/components/Organisms/Markup/Markup.vue
  packages/components/Organisms/Markup/markup.stories.mdx
Labels: needs review

#763 [SDPA-4557] : Adding the new Twitter Social image available in the latest version of tide_site.
  packages/ripple-nuxt-tide/lib/config/tide.config.js
  packages/ripple-nuxt-tide/lib/core/tide-helper.js
  packages/ripple-nuxt-tide/lib/middleware/page-head.js
  packages/ripple-nuxt-tide/test/unit/tide.test.js
Labels: DO NOT MERGE, ready for test

#784 [SDPA-4624] Change CTA img fit to contain
  packages/components/Atoms/ResponsiveImg/ResponsiveImg.vue
  packages/components/Atoms/ResponsiveImg/__snapshots__/stories.storyshot
  packages/components/Molecules/Card/__snapshots__/stories.storyshot
  packages/components/Molecules/Search/__snapshots__/stories.storyshot
  packages/components/Organisms/CallToAction/__snapshots__/stories.storyshot
  packages/components/Organisms/CallToAction/index.vue
  packages/components/Organisms/CallToAction/stories.js
  packages/components/Organisms/CampaignSecondary/__snapshots__/stories.storyshot
  packages/components/Organisms/Event/__snapshots__/stories.storyshot
  packages/components/Organisms/News/__snapshots__/stories.storyshot
Labels: needs review

#790 Fix CTA image positioning for large images
  packages/components/Organisms/CallToAction/index.vue
Labels: needs review

#791 Update callout background colour
  packages/components/Atoms/Global/scss/settings/_colorcore.scss
  packages/components/Atoms/Global/scss/settings/_functions.scss
  packages/components/Organisms/Markup/Markup.vue
Labels: needs review
