Repository dpc-sdp/ripple, pull requests merged in 2020-07, with the labels that each got.

#712 Feature/sdpa 4311 summary not appearing for some contenttypes in search
  packages/ripple-nuxt-tide/modules/search/pages/TideSearch.vue
  packages/ripple-nuxt-tide/modules/search/pages/TopicTagSearch.vue
Labels: ready for test

#714 [DDIDO-200] Update Pre and Post Rollout Tasks (updated Jira script)
  .lagoon.yml
  Dockerfile.app
  Dockerfile.storybook
  scripts/jira-post-comment-app.sh
  scripts/jira-post-comment-storybook.sh
  scripts/jira-post-comment.sh
Labels: needs review

#716 Feature/sdpa 4253 header navigation home link for small screen
  packages/components/Atoms/Icon/assets/img/rpl_icon_menu_home.svg
  packages/components/Organisms/SiteHeader/__snapshots__/stories.storyshot
  packages/components/Organisms/SiteHeader/index.vue
  packages/components/Organisms/SiteHeader/menu.vue
Labels: needs review

#720 [SDPA-4444] Updated css to match the design.
  packages/components/Atoms/MetaTag/index.vue
  packages/components/Molecules/AnchorLinks/index.vue
  packages/components/Organisms/SiteSectionNavigation/index.vue
  packages/ripple-nuxt-tide/lib/middleware/sidebar.js
Labels: needs review

#718 Disable scroll on query param change
  packages/ripple-nuxt-tide/lib/module.js
Labels: needs review

#728 [SDPA-3841] ensure sass variables can be overridden
  packages/components/Atoms/Global/scss/settings/_variables.scss
  packages/components/Molecules/Contact/index.vue
  packages/components/Molecules/Form/Checkbox.vue
  packages/components/Molecules/Form/formAlert.vue
  packages/components/Molecules/Search/SearchResultsTable.vue
  packages/components/Molecules/WhatsNext/index.vue
  packages/components/Organisms/UpdatedDate/index.vue
Labels: ready for test

#730 [SDPA-4339] Fix Oops Banner Not Displaying on Safari
  examples/basic-examples/static/img/oops-banner.svg
  examples/vic-gov-au/static/img/oops-banner.svg
  packages/create-ripple-app/generators/updates/1.26.0/saofile.js
  packages/create-ripple-app/sdp-releases.json
  packages/create-ripple-app/template/nuxt/static/img/oops-banner.svg
Labels: QA complete

#732 [SDPA-4133] Add Hover State to Feedback Form Cancel Button
  packages/components/Atoms/Global/scss/settings/_button.scss
  packages/components/Molecules/Layout/QuickExit.vue
  packages/ripple-nuxt-tide/modules/webform/components/TideContentRating.vue
Labels: QA complete
