Repository dpc-sdp/ripple, pull requests merged in 2020-08, with the labels that each got.

#739 POC - embed IE11 css vars polyfill
  packages/ripple-nuxt-tide/lib/layouts/default.vue
Labels: needs review

#738 Feature/globalise border radius variable
  packages/components/Atoms/Global/scss/settings/_variables.scss
  packages/components/Molecules/Breadcrumbs/index.vue
  packages/components/Molecules/Card/CardContent.vue
  packages/components/Molecules/Card/CardEmergencyContact.vue
  packages/components/Molecules/Card/CardNavigationFeatured.vue
  packages/components/Molecules/Figure/index.vue
  packages/components/Molecules/Form/Checkbox.vue
  packages/components/Molecules/Form/fields/fieldRplchecklist.vue
  packages/components/Molecules/Form/fields/fieldRplslider.vue
  packages/components/Molecules/Form/formAlert.vue
  packages/components/Molecules/Form/formPikaday.vue
  packages/components/Molecules/ListGroup/ListGroup.vue
  packages/components/Molecules/RelatedLinks/index.vue
  packages/components/Molecules/Search/SearchForm.vue
  packages/components/Molecules/WhatsNext/index.vue
  packages/components/Organisms/CallToAction/index.vue
  packages/components/Organisms/CampaignSecondary/index.vue
  packages/components/Organisms/ImageGallery/FullscreenImage.vue
  packages/components/Organisms/ImageGallery/ImageGallery.vue
  packages/components/Organisms/Markup/Markup.vue
  packages/components/Organisms/SiteHeader/index.vue
  packages/components/Organisms/SiteHeader/menu.vue
  packages/components/Organisms/SiteHeader/search.vue
  packages/components/Organisms/SiteSectionNavigation/index.vue
  packages/ripple-nuxt-tide/modules/webform/components/TideContentRating.vue
Labels: needs review

#726 [SDPA-4062] limit max width of body content copy
  .eslintignore
  packages/components/Atoms/Global/scss/settings/_layout.scss
  packages/components/Molecules/DocumentLink/DocumentLink.vue
  packages/components/Molecules/Form/Fieldset.vue
  packages/components/Molecules/Form/index.vue
  packages/components/Molecules/Search/SearchResult.vue
  packages/components/Organisms/Accordion/__snapshots__/stories.storyshot
  packages/components/Organisms/Accordion/stories.js
  packages/components/Organisms/Markup/Markup.vue
Labels: ready to be merged

#745 [SDPA-4106] Added quickexit fix for image gallery modal and IE.
  packages/components/Molecules/Layout/QuickExit.vue
  packages/components/Organisms/ImageGallery/ImageGalleryModal.vue
Labels: ready to be merged

#733 [SDPA-4468] New webform validation
  packages/components/Molecules/Form/index.vue
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
Labels: needs review

#731 [SDPA-4466] Added new var to capture robots meta from page header.
  packages/ripple-nuxt-tide/lib/core/tide-helper.js
  packages/ripple-nuxt-tide/lib/middleware/page-head.js
  packages/ripple-nuxt-tide/test/unit/tide.test.js
Labels: needs review

#754 [SDPA-4307] add table col classes to control width
  packages/components/Atoms/Global/scss/components/_table.scss
  packages/components/Atoms/Global/style.scss
  packages/components/Organisms/Markup/Markup.vue
  packages/components/Organisms/Markup/markup.stories.mdx
  packages/components/Organisms/Markup/stories.js
Labels: QA complete, ready to be merged

#753 [SDPA-4501] add extra validation to search result mapping
  examples/basic-examples/tide/modules/example-search/components/Search.vue
  examples/basic-examples/tide/modules/example-search/components/SearchSimple.vue
  packages/components/Molecules/Search/__tests__/RplSearchForm.test.js
  packages/create-ripple-app/template/_example/tide/modules/event/pages/search.vue
  packages/ripple-nuxt-tide/modules/event/pages/search.vue
  packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
  packages/ripple-nuxt-tide/modules/search/pages/TideSearch.vue
  packages/ripple-nuxt-tide/modules/search/pages/TopicTagSearch.vue
  packages/ripple-nuxt-tide/test/unit/searchmixin.test.js
Labels: QA complete, ready to be merged

#758 [SDPA-4462] update ripple to display multiple contacts in sidebar
  packages/ripple-nuxt-tide/lib/middleware/sidebar.js
Labels: ready to be merged
