Repository dpc-sdp/ripple, pull requests merged in 2020-11, with the labels that each got.

#816 [SW-506] Update TideSearch to use search-results-v2
  packages/components/Molecules/Search/SearchResultsLayout.vue
  packages/components/Molecules/Search/index.js
  packages/ripple-nuxt-tide/modules/search/pages/TideSearch.vue
Labels: needs review

#823 Link / Form / Share colour variables and dark link focus
  packages/components/Atoms/Link/TextLink.vue
  packages/components/Molecules/Alert/__snapshots__/stories.storyshot
  packages/components/Molecules/Form/Fieldset.vue
  packages/components/Molecules/Form/index.vue
  packages/components/Molecules/RelatedLinks/__snapshots__/stories.storyshot
  packages/components/Molecules/ShareThis/index.vue
Labels: needs review

#707 Remove unused variable from tide post.
  packages/ripple-nuxt-tide/lib/core/tide.js
Labels: needs review

#826 [SDPA-4766] Added hero image iin publication and publication page.
  packages/ripple-nuxt-tide/modules/publication/tide.config.js
Labels: needs review

#829 Search form input placeholder colour
  packages/components/Molecules/Search/SearchForm.vue
Labels: needs review

#831 [SDPA-4766] Added hero image field mapping for publication.
  packages/ripple-nuxt-tide/modules/publication/tide.config.js
Labels: needs review

#807 [SDPA-4665] Whatson page returns zero events when reloading
  packages/ripple-nuxt-tide/modules/event/pages/search.vue
Labels: needs review

#828 [SDPA-4817] fix markup for null html
  packages/components/Organisms/Markup/Markup.vue
Labels: needs review

#834 [SDPA-4662] Remove content rating in topic pages
  packages/ripple-nuxt-tide/modules/search/pages/TopicTagSearch.vue
Labels: needs review

#837 [SDPA-4647] update dependencies v2
  Dockerfile.app
  examples/basic-examples/package.json
  examples/vic-gov-au/package.json
  examples/vue-example-app/package.json
  package.json
  packages/components/Atoms/Global/package.json
  packages/components/Molecules/Form/__snapshots__/stories.storyshot
  packages/components/Molecules/Form/__tests__/RplSelect.test.js
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Search/__tests__/RplSearchForm.test.js
  packages/components/Molecules/Search/package.json
  packages/components/Organisms/Grants/package.json
  packages/create-ripple-app/package.json
  packages/ripple-nuxt-tide/lib/module.js
  packages/ripple-nuxt-tide/modules/site/module.js
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  packages/ripple-tide-search-api/package.json
  src/package.json
  yarn.lock
Labels: dependencies, ready for test

#835 [SDPA-4656] assign VIC-Semibold font to strong tag
  packages/components/Organisms/Markup/Markup.vue
Labels: needs review

#838 [SDPA-4247] Fix card event title alignment and padding issue
  packages/components/Molecules/Card/CardEvent.vue
  packages/components/Molecules/Card/stories.js
Labels: ready for test

#839 [SDPA-4764] open/close all accordion feature
  packages/components/Organisms/Accordion/Accordion.vue
  packages/components/Organisms/Accordion/__snapshots__/stories.storyshot
  packages/components/Organisms/Accordion/__tests__/accordion.test.js
  src/.storybook/presets.js
Labels: needs review, ready for test
