Repository dpc-sdp/ripple, pull requests merged in 2021-01, with the labels that each got.

#861 Update Ripple release version to 1.19.3
  examples/basic-examples/package.json
  examples/vic-gov-au/package.json
  examples/vue-example-app/package.json
  lerna.json
  packages/components/Atoms/Button/package.json
  packages/components/Atoms/Global/package.json
  packages/components/Atoms/Grid/package.json
  packages/components/Atoms/Icon/package.json
  packages/components/Atoms/Link/package.json
  packages/components/Atoms/MetaTag/package.json
  packages/components/Atoms/ResponsiveImg/package.json
  packages/components/Molecules/Alert/package.json
  packages/components/Molecules/AnchorLinks/package.json
  packages/components/Molecules/Breadcrumbs/package.json
  packages/components/Molecules/Card/package.json
  packages/components/Molecules/Contact/package.json
  packages/components/Molecules/DescriptionList/package.json
  packages/components/Molecules/DocumentLink/package.json
  packages/components/Molecules/EmbeddedVideo/package.json
  packages/components/Molecules/Figure/package.json
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Layout/package.json
  packages/components/Molecules/List/package.json
  packages/components/Molecules/ListGroup/package.json
  packages/components/Molecules/Pagination/package.json
  packages/components/Molecules/PublishDateAndAuthor/package.json
  packages/components/Molecules/RelatedLinks/package.json
  packages/components/Molecules/Search/package.json
  packages/components/Molecules/ShareThis/package.json
  packages/components/Molecules/Sitemap/package.json
  packages/components/Molecules/Timeline/package.json
  packages/components/Molecules/WhatsNext/package.json
  packages/components/Organisms/Accordion/package.json
  packages/components/Organisms/CallToAction/package.json
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignSecondary/package.json
  packages/components/Organisms/Event/package.json
  packages/components/Organisms/Grants/package.json
  packages/components/Organisms/HeroBanner/package.json
  packages/components/Organisms/ImageGallery/package.json
  packages/components/Organisms/Markup/package.json
  packages/components/Organisms/News/package.json
  packages/components/Organisms/Profile/package.json
  packages/components/Organisms/Publication/package.json
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteHeader/package.json
  packages/components/Organisms/SiteSectionNavigation/package.json
  packages/components/Organisms/UpdatedDate/package.json
  packages/create-ripple-app/package.json
  packages/create-ripple-app/sdp-releases.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  packages/ripple-tide-search-api/package.json
  src/package.json
Labels: ready to be merged

#868 [SDPA-4304] Update documentation template
  packages/components/Atoms/.DS_Store
  packages/components/Atoms/Button/Button.stories.mdx
  packages/components/Atoms/Button/index.vue
  packages/components/Atoms/Global/Global.stories.mdx
  packages/components/Atoms/Grid/Grid.stories.mdx
  packages/components/Atoms/Grid/Grids.stories.mdx
  packages/components/Atoms/Icon/Icon.stories.mdx
  packages/components/Atoms/Icon/Icon.vue
  packages/components/Atoms/Icon/IconLibrary.stories.mdx
  packages/components/Atoms/Icon/README.md
  packages/components/Atoms/Link/Link.stories.mdx
  packages/components/Atoms/MetaTag/MetaTag.stories.mdx
  packages/components/Atoms/MetaTag/index.vue
  packages/components/Atoms/ResponsiveImg/ResponsiveImg.stories.mdx
  packages/components/Molecules/Alert/Alert.stories.mdx
  packages/components/Molecules/AnchorLinks/AnchorLinks.stories.mdx
  packages/components/Molecules/Breadcrumbs/Breadcrumbs.stories.mdx
  packages/components/Molecules/Card/Card.stories.mdx
  packages/components/Molecules/Contact/Contact.stories.mdx
  packages/components/Molecules/DescriptionList/DescriptionList.stories.mdx
  packages/components/Molecules/DocumentLink/DocumentLink.stories.mdx
  packages/components/Molecules/EmbeddedVideo/EmbeddedVideo.stories.mdx
  packages/components/Molecules/Figure/Figure.stories.mdx
  packages/components/Molecules/Form/Form.stories.mdx
  packages/components/Molecules/Layout/Layout.stories.mdx
  packages/components/Molecules/List/List.stories.mdx
  packages/components/Molecules/ListGroup/ListGroup.stories.mdx
  packages/components/Molecules/Pagination/Pagination.stories.mdx
  packages/components/Molecules/PublishDateAndAuthor/PublishedDateAndAuthor.stories.mdx
  packages/components/Molecules/RelatedLinks/RelatedLinks.stories.mdx
  packages/components/Molecules/Search/Search.stories.mdx
  packages/components/Molecules/ShareThis/ShareThis.stories.mdx
  packages/components/Molecules/Sitemap/Sitemap.stories.mdx
  packages/components/Molecules/Timeline/Timeline.stories.mdx
  packages/components/Molecules/WhatsNext/WhatsNext.stories.mdx
  packages/components/Organisms/Accordion/Accordion.stories.mdx
  packages/components/Organisms/CallToAction/CallToAction.stories.mdx
  packages/components/Organisms/CampaignPrimary/CampaignPrimary.stories.mdx
  packages/components/Organisms/CampaignSecondary/CampaignSecondary.stories.mdx
  packages/components/Organisms/Event/Event.stories.mdx
  packages/components/Organisms/Grants/Grants.stories.mdx
  packages/components/Organisms/HeroBanner/heroBanner.stories.mdx
  packages/components/Organisms/HeroBanner/heroBannerCta.stories.mdx
  packages/components/Organisms/HeroBanner/introBanner.stories.mdx
  packages/components/Organisms/ImageGallery/ComplexImage.stories.mdx
  packages/components/Organisms/ImageGallery/ImageGallery.stories.mdx
  packages/components/Organisms/Markup/Markup.stories.mdx
  packages/components/Organisms/News/News.stories.mdx
  packages/components/Organisms/Profile/Profile.stories.mdx
  packages/components/Organisms/Publication/Publication.stories.mdx
  packages/components/Organisms/SiteFooter/SiteFooter.stories.mdx
  packages/components/Organisms/SiteHeader/SiteHeader.stories.mdx
  packages/components/Organisms/SiteSectionNavigation/SiteSectionNavigation.stories.mdx
  packages/components/Organisms/UpdatedDate/UpdatedDate.stories.mdx
  src/static/custom_icons/rpl_icon_custom_icon.js
  src/static/custom_icons/rpl_icon_custom_icon.svg
Labels: needs review

#865 [SDPA-4893] Add max-width to callout markup
  packages/components/Organisms/Markup/Markup.vue
Labels: QA complete

#869 [SDPA-4891] Fix text link multiple spaces issue
  packages/components/Atoms/Icon/TextIcon.vue
  packages/components/Atoms/Icon/__tests__/text-icon.test.js
Labels: bug report, ready to be merged

#847 Feature/SDPA-4876 Added site section name hidden field for content rating form
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  packages/ripple-nuxt-tide/modules/webform/components/TideContentRating.vue
Labels: needs review

#867 [SDPA-4878] Add max-width and update cols setting
  packages/components/Molecules/Card/CardPromo.vue
  packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
Labels: needs review, ready for test

#890 [SDPA-4937] Upgrade nuxt
  .circleci/config.yml
  examples/basic-examples/package.json
  examples/vic-gov-au/package.json
  packages/create-ripple-app/__tests__/__mocks__/v18/package.json
  packages/create-ripple-app/generators/updates/1.31.2/saofile.js
  packages/create-ripple-app/template/_package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  yarn.lock
Labels: needs review
