Repository dpc-sdp/ripple, pull requests merged in 2021-12, with the labels that each got.

#1107 [SDPA-5842] Additional OpenForms styling
  src/static/css/openforms.css
Labels: Needs review

#1108 [SDPSUP-3770] Fixed images not in full width.
  packages/components/Organisms/Markup/Markup.vue
Labels: Ready for test, DO NOT MERGE

#1110 [SDPA-5906] Update high risk dependencies
  examples/basic-examples/package.json
  package.json
  packages/create-ripple-app/package.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-test-tools/package.json
  patches/axios+0.21.4.patch
  yarn.lock
Labels: Ready to be merged

#1106 [SDPA-5894] Replace unicode spaces
  packages/components/Atoms/Global/utils/codepoint.map.json
  packages/components/Organisms/Markup/Markup.stories.mdx
  packages/components/Organisms/Markup/examplePlugins.js
  packages/components/Organisms/Markup/unicode-spaces.md
  packages/ripple-nuxt-tide/lib/config/markup-plugins.js
  packages/ripple-nuxt-tide/test/unit/__fixtures__/markup-transpiler-html.js
  packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
Labels: Ready for test

#1104 [SW-539] Fix elipse radio buttons
  packages/components/Molecules/Form/scss/_form.scss
Labels: Ready to be merged

#1115 [SW-1133] Fix JS error when opening accordions
  packages/components/Organisms/Accordion/Accordion.vue
Labels: Ready to be merged
