Repository dpc-sdp/ripple, pull requests merged in 2021-09, with the labels that each got.

#1020 [SDPA-5283] Fix accordion animation
  packages/components/Organisms/Accordion/Accordion.vue
Labels: ready for test

#1002 [SDPA-5172] lighthouse audit for budget
  packages/components/Molecules/Card/CardCarousel.vue
  packages/components/Molecules/EmbeddedVideo/index.vue
  packages/components/Organisms/ImageGallery/ImageGallery.vue
  packages/components/Organisms/SiteHeader/index.vue
  packages/ripple-nuxt-tide/lib/core/mapping-filters.js
  packages/ripple-nuxt-tide/lib/middleware/banners.js
Labels: needs review

#1000 [SDPA-5217] ordered list spacing
  packages/components/Organisms/Markup/Markup.stories.mdx
  packages/components/Organisms/Markup/Markup.vue
Labels: ready for test, needs review

#1022 [SDPA-5217] Ordering lists
  packages/components/Organisms/Markup/Markup.stories.mdx
  packages/components/Organisms/Markup/Markup.vue
Labels: needs review

#1012 [SDPA-5406] Removed the summary field reference for news attached to the body field.
  packages/ripple-nuxt-tide/modules/landing-page/mapping-filters.js
Labels: needs review

#1026 [SDPA-5363] Increased focus border of Ripple radio buttons from 1px to 3px for better accessibility.
  packages/components/Molecules/Form/scss/_form.scss
Labels: Needs review
