Repository dpc-sdp/ripple, pull requests merged in 2021-07, with the labels that each got.

#978 [SDPA-5304] backport compact card and compact card grid
  packages/components/Molecules/Card/Card.stories.mdx
  packages/components/Molecules/Card/CardCompact.vue
  packages/components/Molecules/Card/CardCompactGrid.vue
  packages/components/Molecules/Card/index.js
Labels: ready for test

#993 [SDPA-5258] Updated metatag to handle the structure change for metatag property in JSON.
  packages/ripple-nuxt-tide/lib/middleware/misc.js
Labels: needs review

#997 [SDPA-5342] Remove featured news mapping as it is removed in BE
  examples/vic-gov-au/test/e2e/integration/smoke/DemoLandingPage.feature
  packages/ripple-nuxt-tide/modules/news/tide.config.js
  packages/ripple-test-tools/step_definitions/components/index.js
Labels: ready to be merged

#998 [SDPA-5254] Changed date format for `ripple-publish-date-and-author` component.
  packages/components/Molecules/PublishDateAndAuthor/index.vue
Labels: needs review

#1005 Fix old reference to card navigation
  examples/vue-example-app/test/e2e/integration/smoke/ripple/step_definition.js
Labels: needs review

#994 [SDPA-5309][SDPA-5051] Improvements to RplSelect
  packages/components/Molecules/Form/Checkbox.vue
  packages/components/Molecules/Form/Form.stories.mdx
  packages/components/Molecules/Form/Select.stories.mdx
  packages/components/Molecules/Form/Select.vue
  packages/components/Molecules/Form/__tests__/RplSelect.test.js
  packages/components/Molecules/Form/fields/fieldRplselect.vue
Labels: needs review, ready for test

#1006 [SRM-93] Fix brand label to have proper capitalisation
  packages/components/Molecules/ShareThis/__test__/ShareThis.test.js
  packages/components/Molecules/ShareThis/index.vue
Labels: ready to be merged

#1007 release/1.23.1
  examples/basic-examples/package.json
  examples/vic-gov-au/package.json
  examples/vue-example-app/package.json
  lerna.json
  packages/components/Atoms/Button/package.json
  packages/components/Atoms/Global/package.json
  packages/components/Atoms/Grid/package.json
  packages/components/Atoms/Icon/package.json
  packages/components/Atoms/Link/package.json
  packages/components/Atoms/MetaTag/package.json
  packages/components/Atoms/ResponsiveImg/package.json
  packages/components/Molecules/Alert/package.json
  packages/components/Molecules/AnchorLinks/package.json
  packages/components/Molecules/Breadcrumbs/package.json
  packages/components/Molecules/Card/package.json
  packages/components/Molecules/Contact/package.json
  packages/components/Molecules/DataTable/package.json
  packages/components/Molecules/DescriptionList/package.json
  packages/components/Molecules/DocumentLink/package.json
  packages/components/Molecules/EmbeddedVideo/package.json
  packages/components/Molecules/Figure/package.json
  packages/components/Molecules/Form/package.json
  packages/components/Molecules/Layout/package.json
  packages/components/Molecules/List/package.json
  packages/components/Molecules/ListGroup/package.json
  packages/components/Molecules/Pagination/package.json
  packages/components/Molecules/PrintThis/package.json
  packages/components/Molecules/PublishDateAndAuthor/package.json
  packages/components/Molecules/RelatedLinks/package.json
  packages/components/Molecules/Search/package.json
  packages/components/Molecules/ShareThis/package.json
  packages/components/Molecules/Sitemap/package.json
  packages/components/Molecules/Timeline/package.json
  packages/components/Molecules/WhatsNext/package.json
  packages/components/Organisms/Accordion/package.json
  packages/components/Organisms/CallToAction/package.json
  packages/components/Organisms/CampaignPrimary/package.json
  packages/components/Organisms/CampaignSecondary/package.json
  packages/components/Organisms/Event/package.json
  packages/components/Organisms/Grants/package.json
  packages/components/Organisms/HeroBanner/package.json
  packages/components/Organisms/ImageGallery/package.json
  packages/components/Organisms/LinkTiles/package.json
  packages/components/Organisms/Markup/package.json
  packages/components/Organisms/News/package.json
  packages/components/Organisms/Profile/package.json
  packages/components/Organisms/Publication/package.json
  packages/components/Organisms/SiteFooter/package.json
  packages/components/Organisms/SiteHeader/package.json
  packages/components/Organisms/SiteSectionNavigation/package.json
  packages/components/Organisms/UpdatedDate/package.json
  packages/create-ripple-app/package.json
  packages/create-ripple-app/sdp-releases.json
  packages/ripple-nuxt-tide/package.json
  packages/ripple-nuxt-ui/package.json
  packages/ripple-test-tools/package.json
  packages/ripple-tide-search-api/package.json
  src/package.json
Labels: needs review

#995 Feature/SDPA-5338 add multilingual patches to core
  packages/components/Atoms/Global/index.js
  packages/components/Atoms/Global/mixins/rtl.js
  packages/components/Atoms/Global/scss/_settings.scss
  packages/components/Atoms/Global/scss/settings/_languages.scss
  packages/components/Atoms/Icon/TextIcon.vue
  packages/components/Molecules/AnchorLinks/index.vue
  packages/components/Molecules/DocumentLink/DocumentLink.vue
  packages/components/Molecules/Layout/PageLayout.vue
  packages/components/Organisms/Accordion/Accordion.vue
  packages/components/Organisms/Markup/Markup.stories.mdx
  packages/components/Organisms/Markup/Markup.vue
  packages/ripple-nuxt-tide/lib/core/middleware.js
  packages/ripple-nuxt-tide/lib/middleware/languages.js
  packages/ripple-nuxt-tide/lib/pages/Sitemap.vue
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
  packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
Labels: needs review
