Repository dpc-sdp/ripple, pull requests merged in 2022-02, with the labels that each got.

#1132 [SRM-295] Revert addition of multiple skip links
  packages/components/Molecules/Layout/BackToTop.vue
  packages/components/Molecules/Layout/SkipLink.vue
  packages/components/Organisms/SiteHeader/index.vue
Labels: QA complete

#1121 [SDPA-5697] - webform radio columns
  packages/components/Molecules/Form/index.vue
Labels: Ready for test

#1133 [SDPA-5957] - Add language font mapping for 'Telugu'
  packages/components/Atoms/Global/scss/generic/_languages.scss
  packages/components/Atoms/Global/scss/settings/_languages.scss
  packages/components/Atoms/Global/style.scss
  packages/components/Molecules/Search/SearchResult.vue
Labels: Needs review

#1138 Content Collection - filter defaultStyling implementation
  packages/ripple-nuxt-tide/modules/landing-page/lib/content-collection.js
Labels: Needs review

#1111 [SDPA-4650] Implemented global footer social links.
  packages/components/Atoms/Icon/icons/email_solid.js
  packages/components/Atoms/Icon/icons/facebook.js
  packages/components/Organisms/SiteFooter/FooterNavigation.vue
  packages/components/Organisms/SiteFooter/FooterSocialLinks.vue
  packages/components/Organisms/SiteFooter/SiteFooter.stories.mdx
  packages/components/Organisms/SiteFooter/SiteFooter.vue
  packages/ripple-nuxt-tide/lib/config/constants.js
  packages/ripple-nuxt-tide/lib/layouts/default.vue
  yarn.lock
Labels: Ready for test

#1153 [SDPA-5281] Content Collection - Add RplMarkup support for description.
  packages/ripple-nuxt-tide/modules/landing-page/components/ContentCollection.vue
Labels: Ready for test

#1156 [SW-1379] - Roll back cheerio to rc.2 to restore IE11 functionality
  packages/components/Organisms/Markup/package.json
  packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
  yarn.lock
Labels: Needs review

#1088 [HEALTHVIC-1281] added topic and tags in news page
  packages/ripple-nuxt-tide/modules/news/pages/index.vue
Labels: Needs review

#1158 [SDPSUP-4025] Fixed CSS for OpenForms with Ripple theme applied
  src/static/css/openforms.css
Labels: Ready to be merged
