Repository dpc-sdp/ripple, pull requests merged in 2022-03, with the labels that each got.

#1159 [SDPA-5922] Sharpen scaled down logos
  packages/components/Organisms/SiteHeader/SiteHeader.stories.mdx
  packages/components/Organisms/SiteHeader/index.scss
  packages/components/Organisms/SiteHeader/index.vue
Labels: Ready to be merged

#1149 [SDPA-5868] Statistics grid
  RIPPLE_COMPONENTS.md
  packages/components/Molecules/Statisticsgrid/.npmignore
  packages/components/Molecules/Statisticsgrid/LICENSE
  packages/components/Molecules/Statisticsgrid/README.md
  packages/components/Molecules/Statisticsgrid/StatisticsGrid.stories.mdx
  packages/components/Molecules/Statisticsgrid/index.vue
  packages/components/Molecules/Statisticsgrid/package.json
  packages/components/Molecules/Statisticsgrid/statistics-grid.scss
  packages/ripple-nuxt-tide/lib/core/component-loader.js
  packages/ripple-nuxt-tide/modules/landing-page/mapping-filters.js
  packages/ripple-nuxt-tide/modules/landing-page/tide.config.js
  packages/ripple-nuxt-tide/package.json
  src/package.json
Labels: Ready to be merged

#1160 [SDPA-5940] Made search scroll to top when pagination changes
  packages/ripple-nuxt-tide/modules/search/lib/searchmixin.js
Labels: Ready for test

#1154 [SDPA-5964] Fix fonts not loading in print by setting display to swap
  packages/components/Atoms/Global/scss/settings/_font.scss
Labels: Ready for test

#1175 [SDPA-6014] - Add feature toggle logic for hardcoded nuxt routes
  packages/ripple-nuxt-tide/modules/event/module.js
  packages/ripple-nuxt-tide/modules/grant/module.js
  packages/ripple-nuxt-tide/modules/profile/module.js
Labels: Needs review
