Repository dpc-sdp/ripple, pull requests merged in 2022-08, with the labels that each got.

#1219 [SDPA-5556] Updated summary field for news search.
  packages/ripple-nuxt-tide/modules/search/pages/TideSearch.vue
  packages/ripple-nuxt-tide/modules/search/pages/TopicTagSearch.vue
Labels: Needs review

#1228 [SDPAP-6333] Added alt text to hero banner logos.
  packages/components/Organisms/HeroBanner/HeroBanner.vue
  packages/components/Organisms/HeroBanner/heroBanner.stories.mdx
  packages/ripple-nuxt-tide/lib/middleware/banners.js
Labels: Ready for test

#1229 [SDPAP-6348] Replace deprecated req call
  packages/ripple-nuxt-tide/lib/templates/plugin.js
Labels: Needs review

#1230 [SDPAP-5916] Updated robots.txt generation so it's part of ripple-nuxt-tide, updated list of excludedPaths.
  examples/basic-examples/nuxt.config.js
  examples/reference/nuxt.config.js
  packages/create-ripple-app/template/nuxt/nuxt.config.js
  packages/ripple-nuxt-tide/README.md
  packages/ripple-nuxt-tide/lib/module.js
Labels: Needs review

#1090 [HEALTHVIC-1187] - added table of content to sitemap
  packages/components/Molecules/Sitemap/README.md
  packages/components/Molecules/Sitemap/Sitemap.stories.mdx
  packages/components/Molecules/Sitemap/SitemapMenu.vue
  packages/components/Molecules/Sitemap/index.vue
  packages/ripple-nuxt-tide/lib/pages/Sitemap.vue
Labels: Needs review

#1231 [SDPAP-6370] Removed most changes from PR 1206, updated accordion titles to h3s
  packages/components/Molecules/AnchorLinks/index.vue
  packages/components/Organisms/Accordion/Accordion.vue
  packages/components/Organisms/Accordion/accordion.scss
  packages/components/Organisms/Accordion/index.js
  packages/ripple-nuxt-tide/lib/pages/Tide.vue
Labels: Needs review

#1222 [SDPA-6117] - Wire up custom string for 'this field is required' error
  README.md
  packages/components/Molecules/Form/index.vue
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
Labels: Needs review

#1236 fix(@dpc-sdp/ripple-form): add default id prefix to forms
  packages/ripple-nuxt-tide/modules/webform/mapping-filters.js
Labels: Ready to be merged
