Repository dpc-sdp/ripple, pull requests merged in 2022-01, with the labels that each got.

#1114 SDPA-5930 - Adjust nav so that 3rd level headings look more clickable
  packages/components/Atoms/Icon/icons/menu_home.js
  packages/components/Organisms/SiteHeader/menu.vue
Labels: Ready for test

#1109 [SDPA-4967] - Added logic to limit nav depth to 3
  packages/components/Organisms/SiteHeader/SiteHeader.stories.mdx
  packages/components/Organisms/SiteHeader/menu.vue
Labels: Ready for test

#1116 [SDPA-5544] - Added icons for spotify and wechat
  packages/components/Atoms/Icon/Icon.stories.mdx
  packages/components/Atoms/Icon/icons/index.js
  packages/components/Atoms/Icon/icons/spotify.js
  packages/components/Atoms/Icon/icons/wechat.js
Labels: Ready for test

#1119 [SDPA-5279] Cheerio update
  jest.config.js
  package.json
  packages/components/Organisms/Markup/examplePlugins.js
  packages/components/Organisms/Markup/markup-transpiler.js
  packages/components/Organisms/Markup/package.json
  packages/ripple-nuxt-tide/lib/config/markup-plugins.js
  packages/ripple-nuxt-tide/test/unit/__fixtures__/markup-transpiler.html
  packages/ripple-nuxt-tide/test/unit/__snapshots__/markup-transpiler.test.js.snap
  packages/ripple-nuxt-tide/test/unit/markup-transpiler.test.js
  yarn.lock
Labels: Ready for test

#1120 [SDPA-5892] Maintain 1:1 aspect on profile image
  packages/components/Organisms/Profile/Profile.stories.mdx
  packages/components/Organisms/Profile/ProfileHighlight.vue
Labels: Ready for test

#1126 Feature/content collection total fix
  packages/ripple-nuxt-tide/modules/landing-page/components/ContentCollection.vue
  packages/ripple-nuxt-tide/modules/landing-page/lib/content-collection.js
Labels: Needs review

#1129 Next event content type
  examples/reference/nuxt.config.ts
  examples/reference/package.json
  package.json
  packages/components/Atoms/Global/scss/utilities/_constrain.scss
  packages/ripple-tide-api/src/controllers/tide-page.js
  packages/ripple-tide-api/src/services/utils/index.js
  packages/ripple-tide-event/definition.yaml
  packages/ripple-tide-event/index.js
  packages/ripple-tide-event/index.vue
  packages/ripple-tide-event/package.json
  packages/ripple-tide-event/utils.js
  yarn.lock
Labels: Needs review, next

#1122 [RPL2-129] Map Grant content type to new API
  _templates/ripple/tide-module/utils.ejs.t
  examples/reference/nuxt.config.ts
  examples/reference/package.json
  examples/reference/static/img/header-pattern-bottom.png
  examples/reference/test/integration/features/grant/contract-grant.feature
  examples/reference/test/integration/features/grant/grant.feature
  examples/reference/test/integration/features/landing-page/homepage.feature
  examples/reference/test/integration/fixtures/grant/sample.json
  package.json
  packages/ripple-nuxt/components/ripple-page.vue
  packages/ripple-test-tools/step_definitions/components/index.js
  packages/ripple-test-tools/step_definitions/modules/grants.js
  packages/ripple-tide-api/src/services/utils/default-mapping.js
  packages/ripple-tide-api/src/services/utils/index.js
  packages/ripple-tide-grant/definition.yaml
  packages/ripple-tide-grant/index.js
  packages/ripple-tide-grant/index.vue
  packages/ripple-tide-grant/package.json
  packages/ripple-tide-grant/utils.js
  packages/ripple-tide-landing-page/index.js
  yarn.lock
Labels: Needs review, next
